// [F:frontend.hook.useWorkspace]
import { act, renderHook, waitFor } from '@testing-library/react'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { useWorkspaceResource } from '@/data/useWorkspace'
import { StagingApiError, type StagingConfig } from '@/data/api/client'

const config: StagingConfig = { baseUrl: 'https://test.invalid', apiKey: 'test' }

function deferred<T>() {
  let resolve!: (value: T) => void
  let reject!: (cause: unknown) => void
  const promise = new Promise<T>((res, rej) => {
    resolve = res
    reject = rej
  })
  return { promise, resolve, reject }
}

afterEach(() => {
  vi.useRealTimers()
  vi.clearAllMocks()
})

describe('useWorkspaceResource lifecycle', () => {
  it('loads once and reports ready with data', async () => {
    const load = vi.fn(async () => 'v1')
    const { result, unmount } = renderHook(() => useWorkspaceResource(config, 'key', load))
    expect(result.current.status).toBe('loading')
    await waitFor(() => expect(result.current.status).toBe('ready'))
    expect(result.current.data).toBe('v1')
    expect(load).toHaveBeenCalledTimes(1)
    expect(load).toHaveBeenCalledWith(config)
    unmount()
  })
  it('never loads without config and key', async () => {
    const load = vi.fn(async () => 'v1')
    const noConfig = renderHook(() => useWorkspaceResource(null, 'key', load))
    expect(noConfig.result.current.status).toBe('offline')
    const noKey = renderHook(() => useWorkspaceResource(config, null, load))
    expect(noKey.result.current.status).toBe('loading')
    await act(async () => {})
    expect(load).not.toHaveBeenCalled()
    noConfig.unmount()
    noKey.unmount()
  })
  it('surfaces a failure and keeps prior data', async () => {
    const load = vi.fn(async () => 'v1')
    const { result, unmount } = renderHook(() => useWorkspaceResource(config, 'key', load))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    load.mockRejectedValueOnce(new Error('fetch down'))
    act(() => result.current.refresh())
    await waitFor(() => expect(result.current.status).toBe('error'))
    expect(result.current.error).toContain('fetch down')
    expect(result.current.data).toBe('v1')
    unmount()
  })
  it('drops data when the failure is denied', async () => {
    const load = vi.fn(async () => 'v1')
    const { result, unmount } = renderHook(() => useWorkspaceResource(config, 'key', load))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    load.mockRejectedValueOnce(new StagingApiError(403, 'forbidden', 'no access'))
    act(() => result.current.refresh())
    await waitFor(() => expect(result.current.status).toBe('denied'))
    expect(result.current.data).toBeUndefined()
    expect(result.current.error).toContain('no access')
    unmount()
  })
  it('falls back to a generic message for non-Error failures', async () => {
    const load = vi.fn(async () => 'v1')
    const { result, unmount } = renderHook(() => useWorkspaceResource(config, 'key', load))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    load.mockRejectedValueOnce('plain failure')
    act(() => result.current.refresh())
    await waitFor(() => expect(result.current.error).toBe('Could not load. Try again.'))
    unmount()
  })
  it('ignores a stale success once a newer attempt resolves', async () => {
    const first = deferred<string>()
    const second = deferred<string>()
    const load = vi.fn().mockResolvedValueOnce(first.promise).mockResolvedValueOnce(second.promise)
    const { result, unmount } = renderHook(() => useWorkspaceResource(config, 'key', load))
    act(() => result.current.refresh())
    await act(async () => { second.resolve('new') })
    await waitFor(() => expect(result.current.data).toBe('new'))
    await act(async () => { first.resolve('old') })
    expect(result.current.data).toBe('new')
    unmount()
  })
  it('ignores a stale failure once a newer attempt succeeded', async () => {
    const first = deferred<string>()
    const second = deferred<string>()
    const load = vi.fn().mockResolvedValueOnce(first.promise).mockResolvedValueOnce(second.promise)
    const { result, unmount } = renderHook(() => useWorkspaceResource(config, 'key', load))
    act(() => result.current.refresh())
    await act(async () => { second.resolve('new') })
    await waitFor(() => expect(result.current.status).toBe('ready'))
    await act(async () => { first.reject(new Error('stale')) })
    expect(result.current.status).toBe('ready')
    expect(result.current.data).toBe('new')
    expect(result.current.error).toBeUndefined()
    unmount()
  })
  it('surfaces a same-attempt failure after acknowledge', async () => {
    const first = deferred<string>()
    const second = deferred<string>()
    const load = vi.fn().mockResolvedValueOnce(first.promise).mockResolvedValueOnce(second.promise)
    const { result, unmount } = renderHook(() => useWorkspaceResource(config, 'key', load))
    let acked = false
    act(() => { acked = result.current.acknowledge('optimistic') })
    expect(acked).toBe(true)
    expect(result.current.data).toBe('optimistic')
    await act(async () => { first.reject(new Error('slow timeout')) })
    await waitFor(() => expect(result.current.status).toBe('error'))
    await act(async () => { second.resolve('fresh') })
    unmount()
  })
  it('resets to loading when the identity changes', async () => {
    const load = vi.fn(async () => 'v1')
    const view = renderHook(({ activeKey }: { activeKey: string | null }) => useWorkspaceResource(config, activeKey, load), { initialProps: { activeKey: 'a' as string | null } })
    await waitFor(() => expect(view.result.current.status).toBe('ready'))
    view.rerender({ activeKey: 'b' })
    expect(view.result.current.status).toBe('loading')
    expect(view.result.current.data).toBeUndefined()
    await waitFor(() => expect(view.result.current.status).toBe('ready'))
    view.rerender({ activeKey: null })
    expect(view.result.current.status).toBe('offline')
    view.unmount()
  })
  it('ignores a settle from the previous identity', async () => {
    const staleFail = deferred<string>()
    const staleWin = deferred<string>()
    const fresh = deferred<string>()
    const load = vi.fn().mockResolvedValueOnce(staleFail.promise).mockResolvedValueOnce(staleWin.promise).mockResolvedValueOnce(fresh.promise)
    const view = renderHook(({ activeKey }: { activeKey: string }) => useWorkspaceResource(config, activeKey, load), { initialProps: { activeKey: 'a' } })
    act(() => view.result.current.refresh())
    view.rerender({ activeKey: 'b' })
    await act(async () => { staleFail.reject(new Error('stale')) })
    expect(view.result.current.status).toBe('loading')
    expect(view.result.current.error).toBeUndefined()
    await act(async () => { staleWin.resolve('stale-data') })
    expect(view.result.current.status).toBe('loading')
    expect(view.result.current.data).toBeUndefined()
    await act(async () => { fresh.resolve('fresh') })
    await waitFor(() => expect(view.result.current.data).toBe('fresh'))
    view.unmount()
  })
  it('honors a changed load function', async () => {
    const first = vi.fn(async () => 'v1')
    const second = vi.fn(async () => 'v2')
    const view = renderHook(({ loader }: { loader: (active: StagingConfig) => Promise<string> }) => useWorkspaceResource(config, 'key', loader), { initialProps: { loader: first } })
    await waitFor(() => expect(view.result.current.data).toBe('v1'))
    view.rerender({ loader: second })
    act(() => view.result.current.refresh())
    await waitFor(() => expect(view.result.current.data).toBe('v2'))
    expect(second).toHaveBeenCalledTimes(1)
    view.unmount()
  })
  it('polls on the default interval', async () => {
    vi.useFakeTimers()
    const load = vi.fn(async () => 'v1')
    const { result, unmount } = renderHook(() => useWorkspaceResource(config, 'key', load, true))
    await act(async () => {})
    expect(load).toHaveBeenCalledTimes(1)
    await act(async () => { vi.advanceTimersByTime(11_000) })
    expect(load).toHaveBeenCalledTimes(3)
    expect(result.current.status).toBe('ready')
    unmount()
  })
  it('honors a custom poll interval', async () => {
    vi.useFakeTimers()
    const load = vi.fn(async () => 'v1')
    const { unmount } = renderHook(() => useWorkspaceResource(config, 'key', load, 100))
    await act(async () => {})
    await act(async () => { vi.advanceTimersByTime(250) })
    expect(load).toHaveBeenCalledTimes(3)
    unmount()
  })
  it('stays quiet without poll and never polls without config', async () => {
    vi.useFakeTimers()
    const load = vi.fn(async () => 'v1')
    const quiet = renderHook(() => useWorkspaceResource(config, 'key', load))
    await act(async () => {})
    await act(async () => { vi.advanceTimersByTime(6_000) })
    expect(load).toHaveBeenCalledTimes(1)
    quiet.unmount()
    const pollingLoad = vi.fn(async () => 'v1')
    const noConfig = renderHook(() => useWorkspaceResource(null, 'key', pollingLoad, true))
    await act(async () => {})
    await act(async () => { vi.advanceTimersByTime(6_000) })
    expect(pollingLoad).not.toHaveBeenCalled()
    noConfig.unmount()
  })
  it('re-arms the interval when poll changes', async () => {
    vi.useFakeTimers()
    const load = vi.fn(async () => 'v1')
    const view = renderHook(({ ms }: { ms: number }) => useWorkspaceResource(config, 'key', load, ms), { initialProps: { ms: 100 } })
    await act(async () => {})
    await act(async () => { vi.advanceTimersByTime(150) })
    expect(load).toHaveBeenCalledTimes(2)
    view.rerender({ ms: 10_000 })
    await act(async () => { vi.advanceTimersByTime(500) })
    expect(load).toHaveBeenCalledTimes(2)
    view.unmount()
  })
  it('refresh reloads with the current loader', async () => {
    const load = vi.fn(async () => 'v1')
    const { result, unmount } = renderHook(() => useWorkspaceResource(config, 'key', load))
    await waitFor(() => expect(result.current.data).toBe('v1'))
    load.mockResolvedValueOnce('v2')
    act(() => result.current.refresh())
    await waitFor(() => expect(result.current.data).toBe('v2'))
    expect(load).toHaveBeenCalledTimes(2)
    unmount()
  })
  it('refresh after key removal does not load', async () => {
    const load = vi.fn(async () => 'v1')
    const view = renderHook(({ activeKey }: { activeKey: string | null }) => useWorkspaceResource(config, activeKey, load), { initialProps: { activeKey: 'a' as string | null } })
    await waitFor(() => expect(view.result.current.status).toBe('ready'))
    view.rerender({ activeKey: null })
    act(() => view.result.current.refresh())
    await act(async () => {})
    expect(load).toHaveBeenCalledTimes(1)
    view.unmount()
  })
  it('acknowledge publishes data and reloads', async () => {
    const load = vi.fn(async () => 'v1')
    const { result, unmount } = renderHook(() => useWorkspaceResource(config, 'key', load))
    await waitFor(() => expect(result.current.data).toBe('v1'))
    load.mockResolvedValueOnce('v2')
    let acked = false
    act(() => { acked = result.current.acknowledge('optimistic') })
    expect(acked).toBe(true)
    expect(result.current.status).toBe('ready')
    expect(result.current.data).toBe('optimistic')
    await waitFor(() => expect(result.current.data).toBe('v2'))
    expect(load).toHaveBeenCalledTimes(2)
    unmount()
  })
  it('acknowledge after identity change returns false and keeps state', async () => {
    const load = vi.fn(async () => 'v1')
    const view = renderHook(({ activeKey }: { activeKey: string }) => useWorkspaceResource(config, activeKey, load), { initialProps: { activeKey: 'a' } })
    await waitFor(() => expect(view.result.current.data).toBe('v1'))
    const staleAck = view.result.current.acknowledge
    view.rerender({ activeKey: 'b' })
    let acked = true
    act(() => { acked = staleAck('stale-write') })
    expect(acked).toBe(false)
    expect(view.result.current.status).toBe('loading')
    expect(view.result.current.data).toBeUndefined()
    let freshAcked = false
    act(() => { freshAcked = view.result.current.acknowledge('current-write') })
    expect(freshAcked).toBe(true)
    expect(view.result.current.data).toBe('current-write')
    view.unmount()
  })
})
