// [F:frontend.hook.useWorkspace]
import { act, renderHook, waitFor } from '@testing-library/react'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { useWorkspaceConversation } from '@/data/useWorkspace'
import { StagingApiError, type StagingConfig } from '@/data/api/client'
import { type LiveThread } from '@/data/api/live'

const mocked = vi.hoisted(() => ({ follow: vi.fn(), history: vi.fn(), send: vi.fn(), steer: vi.fn() }))
vi.mock('@/data/api/live', async (importOriginal) => ({ ...await importOriginal<typeof import('@/data/api/live')>(), followThread: mocked.follow }))
vi.mock('@/data/api/threads', async (importOriginal) => ({ ...await importOriginal<typeof import('@/data/api/threads')>(), listMessages: mocked.history }))
vi.mock('@/data/api/commands', async (importOriginal) => ({ ...await importOriginal<typeof import('@/data/api/commands')>(), sendThreadText: mocked.send, steerThread: mocked.steer }))

const config: StagingConfig = { baseUrl: 'https://test.invalid', apiKey: 'test' }
function channel() {
  const queue: Array<LiveThread | null> = []
  let wake: (() => void) | undefined
  return {
    push(value: LiveThread | null) { queue.push(value); wake?.() },
    async *read(signal?: AbortSignal) {
      while (!signal?.aborted) {
        if (!queue.length) await new Promise<void>((resolve) => { wake = resolve; signal?.addEventListener('abort', () => resolve(), { once: true }) })
        const value = queue.shift()
        if (value === null || signal?.aborted) return
        if (value) yield value
      }
    },
  }
}
const snapshot = (messages: LiveThread['messages']): LiveThread => ({ messages, pendingText: null, pendingReasoning: null, pendingTools: [], error: null })
afterEach(() => { vi.clearAllMocks() })

describe('workspace conversation lifecycle', () => {
  it('closes inactive streams while retaining drafts across conversation switching', async () => {
    const signals = new Map<string, AbortSignal>()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, key: string, signal: AbortSignal) => { signals.set(key, signal); return channel().read(signal) })
    const view = renderHook(({ key }) => useWorkspaceConversation(config, key), { initialProps: { key: 'first' } })
    await waitFor(() => expect(view.result.current.status).toBe('ready'))
    act(() => view.result.current.setDraft('Saved first draft'))
    view.rerender({ key: 'second' })
    await waitFor(() => expect(signals.get('first')?.aborted).toBe(true))
    await waitFor(() => expect(view.result.current.status).toBe('ready'))
    view.rerender({ key: 'first' })
    expect(view.result.current.draft).toBe('Saved first draft')
    await waitFor(() => expect(signals.get('second')?.aborted).toBe(true))
    view.unmount()
  })
  it('reports accepted steering that missed consumption and retains it separately from a newer draft', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.steer.mockResolvedValue({ commandId: 'steer-command', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('Change direction'))
    await act(async () => { await result.current.send(true) })
    act(() => result.current.setDraft('New brainstorming draft'))
    await act(async () => { stream.push({ ...snapshot([{ seq: 5, kind: 'text', role: 'agent', text: 'Old-direction answer' }]), steering: [{ id: 'steer-command', state: 'missed' }] }) })
    await waitFor(() => expect(result.current.busy).toBe(false))
    expect(result.current.draft).toBe('New brainstorming draft')
    expect(result.current.missedInstructions).toEqual(['Change direction'])
    expect(result.current.error).toContain('before steering was applied')
    unmount()
  })
  it('retains accepted pending requests after stream failures when no terminal answer exists', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.send.mockResolvedValue({ commandId: 'running-command', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('Long research'))
    await act(async () => { await result.current.send() })
    act(() => result.current.setDraft('New draft'))
    mocked.history.mockResolvedValue([{ seq: 1, kind: 'text', role: 'user', text: 'Long research' }])
    const failure = { ...snapshot([]), error: new StagingApiError(0, 'stream_idle', 'Silent stream') }
    await act(async () => { stream.push(failure); stream.push(failure); stream.push(failure) })
    await waitFor(() => expect(result.current.error).toContain('may still be running'))
    expect(result.current.busy).toBe(true)
    expect(result.current.pending).toHaveLength(1)
    expect(result.current.draft).toBe('New draft')
    unmount()
  })
  it('does not settle a queued send when the preceding turn finishes', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.send.mockResolvedValue({ commandId: 'queued', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('next request'))
    await act(async () => { await result.current.send() })
    await act(async () => { stream.push(snapshot([{ seq: 2, kind: 'text', role: 'agent', text: 'Earlier answer' }])) })
    expect(result.current.busy).toBe(true)
    await act(async () => { stream.push(snapshot([{ seq: 3, kind: 'text', role: 'user', text: 'next request' }, { seq: 4, kind: 'text', role: 'agent', text: 'Requested answer' }])) })
    await waitFor(() => expect(result.current.busy).toBe(false))
    unmount()
  })
  it('reconnects after graceful EOF rather than leaving the conversation unfollowed', async () => {
    const first = channel(), second = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementationOnce((_config, _key, signal) => first.read(signal)).mockImplementation((_config, _key, signal) => second.read(signal))
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    await act(async () => first.push(null))
    await waitFor(() => expect(mocked.follow).toHaveBeenCalledTimes(2), { timeout: 2500 })
    unmount()
  })
  it('does not overwrite a newer draft when a pending send fails', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    let rejectSend: (error: Error) => void = () => undefined
    mocked.send.mockImplementation(() => new Promise((_resolve, reject) => { rejectSend = reject }))
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('first request'))
    let sending: Promise<void>
    act(() => { sending = result.current.send() })
    act(() => result.current.setDraft('new draft'))
    await act(async () => { rejectSend(new Error('network failed')); await sending })
    expect(result.current.draft).toBe('new draft')
    expect(result.current.error).toContain('network failed')
    unmount()
  })
  it('releases a send when a fresh terminal status arrives without a reply', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.send.mockResolvedValue({ commandId: 'orphan-command', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('Doomed request'))
    await act(async () => { await result.current.send() })
    const user = [{ seq: 1, kind: 'text', role: 'user', text: 'Doomed request' }]
    await act(async () => { stream.push(snapshot(user)) })
    expect(result.current.busy).toBe(true)
    await act(async () => { stream.push({ ...snapshot(user), threadStatus: 'ERROR', threadStatusSeq: 5, stateReason: 'closed-owner' }) })
    await waitFor(() => expect(result.current.busy).toBe(false))
    expect(result.current.pending).toHaveLength(0)
    expect(result.current.live?.stateReason).toBe('closed-owner')
    unmount()
  })
  it('ignores a stale terminal status after a new send', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.send.mockResolvedValue({ commandId: 'second-command', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('First request'))
    await act(async () => { await result.current.send() })
    const first = [{ seq: 1, kind: 'text', role: 'user', text: 'First request' }]
    await act(async () => { stream.push({ ...snapshot(first), threadStatus: 'ERROR', threadStatusSeq: 5 }) })
    await waitFor(() => expect(result.current.busy).toBe(false))
    act(() => result.current.setDraft('Second request'))
    await act(async () => { await result.current.send() })
    const both = [...first, { seq: 2, kind: 'text', role: 'user', text: 'Second request' }]
    await act(async () => { stream.push({ ...snapshot(both), threadStatus: 'ERROR', threadStatusSeq: 5 }) })
    expect(result.current.busy).toBe(true)
    expect(result.current.pending).toHaveLength(1)
    await act(async () => { stream.push({ ...snapshot(both), threadStatus: 'ERROR', threadStatusSeq: 9 }) })
    await waitFor(() => expect(result.current.busy).toBe(false))
    unmount()
  })
  it('stopped() clears in-flight deltas so the indicator cannot resurrect', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.send.mockResolvedValue({ commandId: 'stop-command', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('Doomed request'))
    await act(async () => { await result.current.send() })
    const user = [{ seq: 1, kind: 'text', role: 'user', text: 'Doomed request' }]
    await act(async () => { stream.push({ ...snapshot(user), pendingText: 'partial…' }) })
    expect(result.current.busy).toBe(true)
    act(() => result.current.stopped())
    expect(result.current.busy).toBe(false)
    expect(result.current.phase).toBe('stopped')
    expect(result.current.pending).toEqual([])
    expect(result.current.live?.pendingText).toBeNull()
    expect(result.current.live?.pendingTools).toEqual([])
    unmount()
  })
  it('starts idle with empty conversation state', async () => {
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => channel().read(signal))
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    expect(result.current.phase).toBe('idle')
    expect(result.current.status).toBe('loading')
    expect(result.current.messages).toEqual([])
    expect(result.current.missedInstructions).toEqual([])
    expect(result.current.pending).toEqual([])
    expect(result.current.acknowledgedUsers).toEqual([])
    expect(result.current.busy).toBe(false)
    expect(result.current.echo).toBeNull()
    expect(result.current.live).toBeNull()
    unmount()
  })
  it('restores the draft when steering misses the finished turn', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.steer.mockResolvedValue({ commandId: 'late-steer', state: 'missed_steer' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('Too late'))
    await act(async () => { await result.current.send(true) })
    expect(result.current.pending).toHaveLength(0)
    expect(result.current.busy).toBe(false)
    expect(result.current.echo).toBeNull()
    expect(result.current.draft).toBe('Too late')
    expect(result.current.error).toContain('before steering')
    unmount()
  })
  it('surfaces a stream failure and drops the send queue', async () => {
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation(() => { throw new Error('stream broke') })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.error).toContain('stream broke'))
    expect(result.current.status).toBe('error')
    expect(result.current.busy).toBe(false)
    expect(result.current.pending).toHaveLength(0)
    unmount()
  })
  it('falls back to a generic message for non-Error stream failures', async () => {
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation(() => { throw 'plain break' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.error).toBe('Chat did not load.'))
    expect(result.current.status).toBe('error')
    unmount()
  })
  it('wipes messages and live state when the follower is denied', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([{ seq: 1, kind: 'text', role: 'user', text: 'Old' }])
    mocked.follow.mockImplementationOnce((_config, _key, signal) => stream.read(signal)).mockImplementation(() => { throw new StagingApiError(403, 'forbidden', 'no access') })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.messages).toHaveLength(1))
    await act(async () => { stream.push(null) })
    await waitFor(() => expect(result.current.status).toBe('denied'), { timeout: 2500 })
    expect(result.current.messages).toEqual([])
    expect(result.current.live).toBeNull()
    expect(result.current.error).toContain('no access')
    unmount()
  })
  it('keeps a failed phase across a stream break', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.send.mockRejectedValue(new Error('send down'))
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('Doomed'))
    await act(async () => { await result.current.send() })
    expect(result.current.phase).toBe('failed')
    await act(async () => { stream.push(null) })
    await waitFor(() => expect(mocked.follow).toHaveBeenCalledTimes(2), { timeout: 2500 })
    expect(result.current.phase).toBe('failed')
    unmount()
  })
  it('keeps a stopped phase across a stream break', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.send.mockResolvedValue({ commandId: 'stop-break', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('Halting'))
    await act(async () => { await result.current.send() })
    act(() => result.current.stopped())
    expect(result.current.phase).toBe('stopped')
    await act(async () => { stream.push(null) })
    await waitFor(() => expect(mocked.follow).toHaveBeenCalledTimes(2), { timeout: 2500 })
    expect(result.current.phase).toBe('stopped')
    unmount()
  })
  it('keeps a paused phase across a stream break', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    await act(async () => { stream.push({ ...snapshot([]), threadStatus: 'PAUSED', threadStatusSeq: 3 }) })
    expect(result.current.phase).toBe('paused')
    await act(async () => { stream.push(null) })
    await waitFor(() => expect(mocked.follow).toHaveBeenCalledTimes(2), { timeout: 2500 })
    expect(result.current.phase).toBe('paused')
    unmount()
  })
  it('marks the conversation reconnecting across a stream break', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    await act(async () => { stream.push(null) })
    await waitFor(() => expect(result.current.phase).toBe('reconnecting'))
    await waitFor(() => expect(mocked.follow).toHaveBeenCalledTimes(2), { timeout: 2500 })
    unmount()
  })
  it('does not start a follower for a null key', async () => {
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => channel().read(signal))
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, null))
    expect(mocked.follow).not.toHaveBeenCalled()
    expect(result.current.status).toBe('loading')
    unmount()
  })
  it('aborts the follower on unmount', async () => {
    let seen: AbortSignal | undefined
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => { seen = signal; return channel().read(signal) })
    const { unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(mocked.follow).toHaveBeenCalledTimes(1))
    unmount()
    expect(seen?.aborted).toBe(true)
  })
  it('aborts the old follower and follows with the new config', async () => {
    const signals: AbortSignal[] = []
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => { signals.push(signal); return channel().read(signal) })
    const view = renderHook(({ active }) => useWorkspaceConversation(active, 'thread'), { initialProps: { active: config } })
    await waitFor(() => expect(view.result.current.status).toBe('ready'))
    const rotated: StagingConfig = { baseUrl: 'https://rotated.invalid', apiKey: 'rotated' }
    view.rerender({ active: rotated })
    await waitFor(() => expect(mocked.follow).toHaveBeenCalledTimes(2))
    expect(signals[0]?.aborted).toBe(true)
    expect(mocked.follow).toHaveBeenLastCalledWith(rotated, 'thread', expect.anything(), { cursor: { seq: 0 } })
    expect(view.result.current.status).toBe('ready')
    view.unmount()
  })
  it('starts a fresh follow from zero after a send while already following', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.send.mockResolvedValue({ commandId: 'again', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    expect(mocked.follow).toHaveBeenCalledWith(config, 'thread', expect.anything(), { cursor: { seq: 0 } })
    act(() => result.current.setDraft('Second'))
    await act(async () => { await result.current.send() })
    expect(mocked.follow).toHaveBeenCalledTimes(1)
    unmount()
  })
  it('restarts the follower after recovery drops the stale controller', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.send.mockResolvedValue({ commandId: 'post-recovery', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('Before recovery'))
    await act(async () => { await result.current.send() })
    const failure = { ...snapshot([]), pendingText: 'stale…', pendingTools: [{ runKey: 'r1', id: 't1', name: 'search', state: 'running' }], error: new StagingApiError(0, 'stream_idle', 'Silent stream') }
    await act(async () => { stream.push(failure); stream.push(failure); stream.push(failure) })
    await waitFor(() => expect(result.current.error).toContain('may still be running'))
    expect(result.current.live?.pendingText).toBeNull()
    expect(result.current.live?.pendingReasoning).toBeNull()
    expect(result.current.live?.pendingTools).toEqual([])
    act(() => result.current.setDraft('After recovery'))
    await act(async () => { await result.current.send() })
    await waitFor(() => expect(mocked.follow).toHaveBeenCalledTimes(2))
    unmount()
  })
  it('ignores a superseded load when the key rotates mid-flight', async () => {
    let resolveHistory: (value: unknown[]) => void = () => undefined
    mocked.history.mockImplementation(() => new Promise((resolve) => { resolveHistory = resolve }))
    mocked.follow.mockImplementation((_config, _key, signal) => channel().read(signal))
    const view = renderHook(({ key }) => useWorkspaceConversation(config, key), { initialProps: { key: 'first' } })
    view.rerender({ key: 'second' })
    await act(async () => { resolveHistory([]) })
    await waitFor(() => expect(view.result.current.status).toBe('ready'))
    view.rerender({ key: 'first' })
    expect(view.result.current.status).toBe('loading')
    expect(view.result.current.messages).toEqual([])
    view.unmount()
  })
  it('ignores stream frames for a key rotated away mid-stream', async () => {
    const first = channel(), second = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, key: string, signal) => (key === 'first' ? first : second).read(signal))
    const view = renderHook(({ key }) => useWorkspaceConversation(config, key), { initialProps: { key: 'first' } })
    await waitFor(() => expect(view.result.current.status).toBe('ready'))
    view.rerender({ key: 'second' })
    await waitFor(() => expect(view.result.current.status).toBe('ready'))
    await act(async () => { first.push(snapshot([{ seq: 1, kind: 'text', role: 'agent', text: 'Stale answer' }])) })
    view.rerender({ key: 'first' })
    expect(view.result.current.messages).toEqual([])
    view.unmount()
  })
  it('ignores a reread that resolves after the key rotated away', async () => {
    const first = channel()
    let resolveReread: (value: unknown[]) => void = () => undefined
    mocked.history.mockResolvedValueOnce([]).mockImplementationOnce(() => new Promise((resolve) => { resolveReread = resolve as (value: unknown[]) => void })).mockResolvedValue([])
    mocked.follow.mockImplementation((_config, key: string, signal) => (key === 'first' ? first : channel()).read(signal))
    const view = renderHook(({ key }) => useWorkspaceConversation(config, key), { initialProps: { key: 'first' } })
    await waitFor(() => expect(view.result.current.status).toBe('ready'))
    const failure = { ...snapshot([]), error: new StagingApiError(0, 'stream_idle', 'Silent stream') }
    await act(async () => { first.push(failure); first.push(failure); first.push(failure) })
    view.rerender({ key: 'second' })
    await act(async () => { resolveReread([]) })
    view.rerender({ key: 'first' })
    expect(view.result.current.error).toBeNull()
    view.unmount()
  })
  it('keeps the newest follower after a rapid rotation', async () => {
    const signals = new Map<string, AbortSignal[]>()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, key: string, signal) => {
      const prior = signals.get(key) ?? []
      signals.set(key, [...prior, signal])
      return channel().read(signal)
    })
    const view = renderHook(({ key }) => useWorkspaceConversation(config, key), { initialProps: { key: 'first' } })
    await waitFor(() => expect(view.result.current.status).toBe('ready'))
    view.rerender({ key: 'second' })
    view.rerender({ key: 'first' })
    await waitFor(() => expect(signals.get('first')).toHaveLength(2))
    view.unmount()
    const latest = signals.get('first')?.[1]
    expect(latest?.aborted).toBe(true)
  })
  it('drops a late send completion after the config rotates', async () => {
    let resolveSteer: (value: { commandId: string; state: string }) => void = () => undefined
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => channel().read(signal))
    mocked.steer.mockImplementation(() => new Promise((resolve) => { resolveSteer = resolve as (value: { commandId: string; state: string }) => void }))
    const view = renderHook(({ active }) => useWorkspaceConversation(active, 'thread'), { initialProps: { active: config } })
    await waitFor(() => expect(view.result.current.status).toBe('ready'))
    act(() => view.result.current.setDraft('Rotating steer'))
    let sending: Promise<void>
    act(() => { sending = view.result.current.send(true) })
    view.rerender({ active: { baseUrl: 'https://rotated.invalid', apiKey: 'rotated' } })
    await act(async () => { resolveSteer({ commandId: 'late', state: 'missed_steer' }); await sending })
    expect(view.result.current.draft).toBe('')
    expect(view.result.current.error).toBeNull()
    expect(view.result.current.pending).toHaveLength(0)
    view.unmount()
  })
  it('drops a late send failure after the config rotates', async () => {
    let rejectSend: (error: Error) => void = () => undefined
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => channel().read(signal))
    mocked.send.mockImplementation(() => new Promise((_resolve, reject) => { rejectSend = reject }))
    const view = renderHook(({ active }) => useWorkspaceConversation(active, 'thread'), { initialProps: { active: config } })
    await waitFor(() => expect(view.result.current.status).toBe('ready'))
    act(() => view.result.current.setDraft('Rotating send'))
    let sending: Promise<void>
    act(() => { sending = view.result.current.send() })
    view.rerender({ active: { baseUrl: 'https://rotated.invalid', apiKey: 'rotated' } })
    await act(async () => { rejectSend(new Error('too late')); await sending })
    expect(view.result.current.phase).toBe('idle')
    expect(view.result.current.error).toBeNull()
    view.unmount()
  })
  it('holds steering until its consumption receipt, then releases on the reply', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.steer.mockResolvedValue({ commandId: 's1', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('Steer me'))
    await act(async () => { await result.current.send(true) })
    const reply = [{ seq: 5, kind: 'text', role: 'agent', text: 'Steered answer' }]
    await act(async () => { stream.push(snapshot(reply)) })
    expect(result.current.pending).toHaveLength(1)
    expect(result.current.busy).toBe(true)
    await act(async () => { stream.push({ ...snapshot(reply), steering: [{ id: 'other', state: 'missed' }, { id: 's1', state: 'consumed' }] }) })
    await waitFor(() => expect(result.current.busy).toBe(false))
    expect(result.current.pending).toHaveLength(0)
    expect(result.current.missedInstructions).toEqual([])
    unmount()
  })
  it('does not mistake another steer receipt for this steer', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.steer.mockResolvedValue({ commandId: 's1', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('Steer me'))
    await act(async () => { await result.current.send(true) })
    await act(async () => { stream.push({ ...snapshot([]), steering: [{ id: 'other', state: 'missed' }] }) })
    expect(result.current.pending).toHaveLength(1)
    expect(result.current.missedInstructions).toEqual([])
    expect(result.current.error).toBeNull()
    unmount()
  })
  it('does not file a normal send under missed steering', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.send.mockResolvedValue({ commandId: 'normal', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('Normal send'))
    await act(async () => { await result.current.send() })
    await act(async () => { stream.push({ ...snapshot([]), steering: [{ id: 'normal', state: 'missed' }] }) })
    expect(result.current.busy).toBe(true)
    expect(result.current.pending).toHaveLength(1)
    expect(result.current.missedInstructions).toEqual([])
    unmount()
  })
  it('acks the echoed user message once and never re-acks a duplicate', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.send.mockResolvedValue({ commandId: 'ack', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('Hello'))
    await act(async () => { await result.current.send() })
    const user = [{ seq: 1, kind: 'text', role: 'user', text: 'Hello' }]
    await act(async () => { stream.push(snapshot(user)) })
    expect(result.current.acknowledgedUsers).toEqual([1])
    expect(result.current.pending).toHaveLength(1)
    await act(async () => { stream.push(snapshot([...user, { seq: 2, kind: 'text', role: 'user', text: 'Hello' }])) })
    expect(result.current.acknowledgedUsers).toEqual([1])
    await act(async () => { stream.push(snapshot([...user, { seq: 3, kind: 'text', role: 'agent', text: 'Hi' }])) })
    await waitFor(() => expect(result.current.busy).toBe(false))
    unmount()
  })
  it('ignores user messages at or below the send basis', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([{ seq: 1, kind: 'text', role: 'user', text: 'Hello' }])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.send.mockResolvedValue({ commandId: 'basis', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.messages).toHaveLength(1))
    act(() => result.current.setDraft('Hello'))
    await act(async () => { await result.current.send() })
    await act(async () => { stream.push(snapshot([{ seq: 1, kind: 'text', role: 'user', text: 'Hello' }])) })
    expect(result.current.acknowledgedUsers).toEqual([])
    expect(result.current.busy).toBe(true)
    unmount()
  })
  it('matches user messages by exact text, role, and kind', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.send.mockResolvedValue({ commandId: 'exact', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('Alpha'))
    await act(async () => { await result.current.send() })
    await act(async () => { stream.push(snapshot([{ seq: 1, kind: 'text', role: 'user', text: 'Beta' }])) })
    expect(result.current.acknowledgedUsers).toEqual([])
    await act(async () => { stream.push(snapshot([{ seq: 2, kind: 'text', role: 'agent', text: 'Alpha' }])) })
    expect(result.current.acknowledgedUsers).toEqual([])
    await act(async () => { stream.push(snapshot([{ seq: 3, kind: 'tool', name: 'Alpha', detail: '', state: 'done' }])) })
    expect(result.current.acknowledgedUsers).toEqual([])
    expect(result.current.busy).toBe(true)
    unmount()
  })
  it('holds the send when in-flight deltas outrank a fresh terminal status', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.send.mockResolvedValue({ commandId: 'inflight', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('Streaming'))
    await act(async () => { await result.current.send() })
    const user = [{ seq: 1, kind: 'text', role: 'user', text: 'Streaming' }]
    await act(async () => { stream.push({ ...snapshot(user), pendingText: 'partial…', threadStatus: 'ERROR', threadStatusSeq: 5 }) })
    expect(result.current.busy).toBe(true)
    expect(result.current.pending).toHaveLength(1)
    await act(async () => { stream.push({ ...snapshot(user), pendingReasoning: 'thinking…', threadStatus: 'ERROR', threadStatusSeq: 6 }) })
    expect(result.current.busy).toBe(true)
    await act(async () => { stream.push({ ...snapshot(user), pendingTools: [{ runKey: 'r1', id: 't1', name: 'search', state: 'running' }], threadStatus: 'ERROR', threadStatusSeq: 7 }) })
    expect(result.current.busy).toBe(true)
    unmount()
  })
  it('releases on a fresh terminal status once no tool still runs', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.send.mockResolvedValue({ commandId: 'tools-done', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('Tooled'))
    await act(async () => { await result.current.send() })
    const user = [{ seq: 1, kind: 'text', role: 'user', text: 'Tooled' }]
    await act(async () => { stream.push({ ...snapshot(user), pendingTools: [{ runKey: 'r1', id: 't1', name: 'search', state: 'done' }], threadStatus: 'ERROR', threadStatusSeq: 5 }) })
    await waitFor(() => expect(result.current.busy).toBe(false))
    unmount()
  })
  it('matches a reply only past the user message seq', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.send.mockResolvedValue({ commandId: 'boundary', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('Boundary'))
    await act(async () => { await result.current.send() })
    const user = [{ seq: 1, kind: 'text', role: 'user', text: 'Boundary' }]
    await act(async () => { stream.push(snapshot([...user, { seq: 1, kind: 'text', role: 'agent', text: 'Same-seq note' }])) })
    expect(result.current.busy).toBe(true)
    await act(async () => { stream.push(snapshot([...user, { seq: 2, kind: 'text', role: 'user', text: 'Boundary' }])) })
    expect(result.current.busy).toBe(true)
    await act(async () => { stream.push(snapshot([...user, { seq: 3, kind: 'tool', name: 'search', detail: '', state: 'done' }])) })
    expect(result.current.busy).toBe(true)
    await act(async () => { stream.push(snapshot([...user, { seq: 4, kind: 'text', role: 'agent', text: 'Real answer' }])) })
    await waitFor(() => expect(result.current.busy).toBe(false))
    unmount()
  })
  it('echoes the unacked send until the user message lands, never steering', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.send.mockResolvedValue({ commandId: 'echo', state: 'accepted' })
    mocked.steer.mockResolvedValue({ commandId: 'echo-steer', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('Echo me'))
    await act(async () => { await result.current.send() })
    expect(result.current.echo).toBe('Echo me')
    const user = [{ seq: 1, kind: 'text', role: 'user', text: 'Echo me' }]
    await act(async () => { stream.push(snapshot(user)) })
    expect(result.current.echo).toBeNull()
    act(() => result.current.setDraft('Steer quietly'))
    await act(async () => { await result.current.send(true) })
    expect(result.current.echo).toBeNull()
    unmount()
  })
  it('clears the recovery error on a clean frame and keeps it on a failing one', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.send.mockResolvedValue({ commandId: 'recover-clear', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('Flaky'))
    await act(async () => { await result.current.send() })
    const failure = { ...snapshot([]), error: new StagingApiError(0, 'stream_idle', 'Silent stream') }
    await act(async () => { stream.push(failure); stream.push(failure); stream.push(failure) })
    await waitFor(() => expect(result.current.error).toContain('may still be running'))
    act(() => result.current.retry())
    await waitFor(() => expect(mocked.follow).toHaveBeenCalledTimes(2))
    await act(async () => { stream.push({ ...snapshot([]), error: new StagingApiError(0, 'stream_idle', 'Again') }) })
    expect(result.current.error).not.toBeNull()
    await act(async () => { stream.push(snapshot([])) })
    await waitFor(() => expect(result.current.error).toBeNull())
    expect(result.current.phase).toBe('queued')
    unmount()
  })
  it('keeps a send failure error across clean frames', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.send.mockRejectedValue(new Error('send down'))
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('Doomed'))
    await act(async () => { await result.current.send() })
    expect(result.current.error).toContain('send down')
    await act(async () => { stream.push(snapshot([])) })
    expect(result.current.error).toContain('send down')
    unmount()
  })
  it('joins missed steers into an empty draft', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.steer.mockResolvedValueOnce({ commandId: 'm1', state: 'accepted' }).mockResolvedValueOnce({ commandId: 'm2', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('First steer'))
    await act(async () => { await result.current.send(true) })
    act(() => result.current.setDraft('Second steer'))
    await act(async () => { await result.current.send(true) })
    await act(async () => { stream.push({ ...snapshot([]), steering: [{ id: 'm1', state: 'missed' }, { id: 'm2', state: 'missed' }] }) })
    await waitFor(() => expect(result.current.missedInstructions).toEqual(['First steer', 'Second steer']))
    expect(result.current.draft).toBe('First steer\n\nSecond steer')
    expect(result.current.error).toContain('before steering was applied')
    unmount()
  })
  it('reports queued until the send is acked, then working', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.send.mockResolvedValue({ commandId: 'phase', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('Phase me'))
    await act(async () => { await result.current.send() })
    expect(result.current.phase).toBe('queued')
    expect(result.current.busy).toBe(true)
    expect(result.current.draft).toBe('')
    const user = [{ seq: 1, kind: 'text', role: 'user', text: 'Phase me' }]
    await act(async () => { stream.push(snapshot(user)) })
    expect(result.current.phase).toBe('working')
    await act(async () => { stream.push(snapshot([...user, { seq: 2, kind: 'text', role: 'agent', text: 'Done' }])) })
    await waitFor(() => expect(result.current.phase).toBe('complete'))
    unmount()
  })
  it('reports working when any send is acked', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.send.mockResolvedValueOnce({ commandId: 'p1', state: 'accepted' }).mockResolvedValueOnce({ commandId: 'p2', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('First'))
    await act(async () => { await result.current.send() })
    act(() => result.current.setDraft('Second'))
    await act(async () => { await result.current.send() })
    expect(result.current.phase).toBe('queued')
    await act(async () => { stream.push(snapshot([{ seq: 1, kind: 'text', role: 'user', text: 'First' }])) })
    expect(result.current.phase).toBe('working')
    unmount()
  })
  it('reports steering as working once live state exists', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.steer.mockResolvedValue({ commandId: 'phase-steer', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    await act(async () => { stream.push(snapshot([])) })
    act(() => result.current.setDraft('Steer phase'))
    await act(async () => { await result.current.send(true) })
    expect(result.current.phase).toBe('working')
    unmount()
  })
  it('reports working while deltas stream with no send owed', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    await act(async () => { stream.push({ ...snapshot([]), pendingText: 'background…' }) })
    expect(result.current.phase).toBe('working')
    expect(result.current.busy).toBe(true)
    unmount()
  })
  it('settles back to idle after a quiet reconnect', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    await act(async () => { stream.push(null) })
    await waitFor(() => expect(result.current.phase).toBe('reconnecting'))
    await waitFor(() => expect(mocked.follow).toHaveBeenCalledTimes(2), { timeout: 2500 })
    await act(async () => { stream.push(snapshot([])) })
    await waitFor(() => expect(result.current.phase).toBe('idle'))
    unmount()
  })
  it('ignores an empty send and keeps the draft', async () => {
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => channel().read(signal))
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('   '))
    await act(async () => { await result.current.send() })
    expect(mocked.send).not.toHaveBeenCalled()
    expect(result.current.pending).toHaveLength(0)
    expect(result.current.draft).toBe('   ')
    expect(result.current.busy).toBe(false)
    unmount()
  })
  it('ignores a send with no config', async () => {
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => channel().read(signal))
    const { result, unmount } = renderHook(() => useWorkspaceConversation(null, 'thread'))
    act(() => result.current.setDraft('Nowhere'))
    await act(async () => { await result.current.send() })
    expect(mocked.send).not.toHaveBeenCalled()
    expect(result.current.pending).toHaveLength(0)
    unmount()
  })
  it('holds the draft when offline instead of sending', async () => {
    Object.defineProperty(window.navigator, 'onLine', { value: false, configurable: true })
    try {
      mocked.history.mockResolvedValue([])
      mocked.follow.mockImplementation((_config, _key, signal) => channel().read(signal))
      const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
      await waitFor(() => expect(result.current.status).toBe('ready'))
      act(() => result.current.setDraft('Offline draft'))
      await act(async () => { await result.current.send() })
      expect(mocked.send).not.toHaveBeenCalled()
      expect(result.current.pending).toHaveLength(0)
      expect(result.current.error).toContain('No connection')
      unmount()
    } finally {
      Object.defineProperty(window.navigator, 'onLine', { value: true, configurable: true })
    }
  })
  it('sends explicit text instead of the draft', async () => {
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => channel().read(signal))
    mocked.send.mockResolvedValue({ commandId: 'explicit', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('Draft text'))
    await act(async () => { await result.current.send(false, 'Explicit text') })
    expect(mocked.send).toHaveBeenCalledWith(config, 'thread', 'Explicit text')
    expect(result.current.echo).toBe('Explicit text')
    unmount()
  })
  it('keys concurrent sends in order', async () => {
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => channel().read(signal))
    mocked.send.mockResolvedValue({ commandId: 'keyed', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('One'))
    await act(async () => { await result.current.send() })
    act(() => result.current.setDraft('Two'))
    await act(async () => { await result.current.send() })
    expect(result.current.pending.map((request) => request.key)).toEqual([1, 2])
    unmount()
  })
  it('bases a steer past the heaviest known message', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([{ seq: 5, kind: 'text', role: 'agent', text: 'Old answer' }])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    mocked.steer.mockResolvedValue({ commandId: 'based', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.messages).toHaveLength(1))
    act(() => result.current.setDraft('Steer on'))
    await act(async () => { await result.current.send(true) })
    const known = [{ seq: 5, kind: 'text', role: 'agent', text: 'Old answer' }]
    await act(async () => { stream.push({ ...snapshot(known), steering: [{ id: 'based', state: 'consumed' }] }) })
    expect(result.current.busy).toBe(true)
    expect(result.current.pending).toHaveLength(1)
    unmount()
  })
  it('attaches the command id to the completing send only', async () => {
    const stream = channel()
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => stream.read(signal))
    const resolvers: Array<(value: { commandId: string; state: string }) => void> = []
    mocked.steer.mockImplementation(() => new Promise((resolve) => { resolvers.push(resolve as (value: { commandId: string; state: string }) => void) }))
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('S1'))
    let first: Promise<void>
    act(() => { first = result.current.send(true) })
    act(() => result.current.setDraft('S2'))
    act(() => { void result.current.send(true) })
    await act(async () => { resolvers[0]?.({ commandId: 'c1', state: 'accepted' }); await first })
    await act(async () => { stream.push({ ...snapshot([]), steering: [{ id: 'c1', state: 'missed' }] }) })
    await waitFor(() => expect(result.current.missedInstructions).toEqual(['S1']))
    expect(result.current.pending).toHaveLength(1)
    expect(result.current.pending[0]?.text).toBe('S2')
    unmount()
  })
  it('fails a lone send with an empty queue', async () => {
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => channel().read(signal))
    mocked.send.mockRejectedValue(new Error('send down'))
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('Doomed'))
    await act(async () => { await result.current.send() })
    expect(result.current.phase).toBe('failed')
    expect(result.current.busy).toBe(false)
    expect(result.current.pending).toHaveLength(0)
    expect(result.current.echo).toBeNull()
    expect(result.current.error).toContain('send down')
    unmount()
  })
  it('falls back to a generic message for non-Error send failures', async () => {
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => channel().read(signal))
    mocked.send.mockRejectedValue('plain failure')
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('Doomed'))
    await act(async () => { await result.current.send() })
    expect(result.current.error).toBe('Send failed. Your draft is saved.')
    unmount()
  })
  it('keeps the surviving send busy when its sibling fails', async () => {
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => channel().read(signal))
    let rejectFirst: (error: Error) => void = () => undefined
    mocked.send.mockImplementationOnce(() => new Promise((_resolve, reject) => { rejectFirst = reject })).mockResolvedValue({ commandId: 'sibling', state: 'accepted' })
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, 'thread'))
    await waitFor(() => expect(result.current.status).toBe('ready'))
    act(() => result.current.setDraft('A'))
    let first: Promise<void>
    act(() => { first = result.current.send() })
    act(() => result.current.setDraft('B'))
    await act(async () => { await result.current.send() })
    await act(async () => { rejectFirst(new Error('A failed')); await first })
    expect(result.current.pending).toHaveLength(1)
    expect(result.current.pending[0]?.text).toBe('B')
    expect(result.current.busy).toBe(true)
    expect(result.current.draft).toBe('A')
    unmount()
  })
  it('ignores retry with no thread key', async () => {
    mocked.history.mockResolvedValue([])
    mocked.follow.mockImplementation((_config, _key, signal) => channel().read(signal))
    const { result, unmount } = renderHook(() => useWorkspaceConversation(config, null))
    act(() => result.current.retry())
    expect(mocked.follow).not.toHaveBeenCalled()
    unmount()
  })
})
