// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.chat.MessageBubble",
  "route": "/?section=SectorChat&sector=sector-matrix&session=mx-session-001&thread=mx-session-001",
  "primary": "messages"
}

test('[F:frontend.src.components.chat.MessageBubble] MessageBubble typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[aria-label=\"Conversation messages\"]"}] }, 'typical')
})

test('[F:frontend.src.components.chat.MessageBubble] MessageBubble one', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[aria-label=\"Conversation messages\"]"}] }, 'one')
})

test('[F:frontend.src.components.chat.MessageBubble] MessageBubble n100', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[aria-label=\"Conversation messages\"]"}] }, 'n100')
})

test('[F:frontend.src.components.chat.MessageBubble] MessageBubble n1000', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[aria-label=\"Conversation messages\"]"}] }, 'n1000')
})

test('[F:frontend.src.components.chat.MessageBubble] MessageBubble longtext', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[aria-label=\"Conversation messages\"]"}] }, 'longtext')
})

test('[F:frontend.src.components.chat.MessageBubble] MessageBubble dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[aria-label=\"Conversation messages\"]"}] }, 'dark')
})

test('[F:frontend.src.components.chat.MessageBubble] MessageBubble w390', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[aria-label=\"Conversation messages\"]"}] }, 'w390')
})
