// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.chat.SessionsPanel",
  "route": "/",
  "gated": true,
  "setup": [
    {
      "click": {
        "kind": "role",
        "role": "button",
        "name": "Ask Karbot"
      }
    },
    {
      "click": {
        "kind": "css",
        "css": "[aria-label=\"Chat sessions\"]"
      }
    }
  ],
  "postAnchors": [
    {
      "kind": "role",
      "role": "complementary",
      "name": "Assistant chat"
    },
    {
      "kind": "text",
      "text": "New chat"
    }
  ],
  "primary": "sessions"
}

test('[F:frontend.src.components.chat.SessionsPanel] SessionsPanel typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"button","name":"Ask Karbot"}], expectedRows: { selector: "[aria-label=\"Chat sessions\"] [role=\"menuitem\"][aria-label^=\"Open \"]", count: 8 } }, 'typical')
})

test('[F:frontend.src.components.chat.SessionsPanel] SessionsPanel n100', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"button","name":"Ask Karbot"}], expectedRows: { selector: "[aria-label=\"Chat sessions\"] [role=\"menuitem\"][aria-label^=\"Open \"]", count: 100 } }, 'n100')
})

test('[F:frontend.src.components.chat.SessionsPanel] SessionsPanel dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"button","name":"Ask Karbot"}] }, 'dark')
})

test('[F:frontend.src.components.chat.SessionsPanel] SessionsPanel w390', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"button","name":"Ask Karbot"}] }, 'w390')
})

test('[F:frontend.src.components.chat.SessionsPanel] SessionsPanel focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"button","name":"Ask Karbot"}] }, 'focus')
})
