// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.chat.ChatComposer",
  "route": "/",
  "setup": [
    {
      "click": {
        "kind": "role",
        "role": "button",
        "name": "Ask Karbot"
      }
    }
  ],
  "primary": "messages"
}

test('[F:frontend.src.components.chat.ChatComposer] ChatComposer typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"complementary","name":"Assistant chat"},{"kind":"role","role":"textbox"},{"kind":"role","role":"button","name":"Attach file"}] }, 'typical')
})

test('[F:frontend.src.components.chat.ChatComposer] ChatComposer dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"complementary","name":"Assistant chat"},{"kind":"role","role":"textbox"},{"kind":"role","role":"button","name":"Attach file"}] }, 'dark')
})

test('[F:frontend.src.components.chat.ChatComposer] ChatComposer w390', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"complementary","name":"Assistant chat"},{"kind":"role","role":"textbox"},{"kind":"role","role":"button","name":"Attach file"}] }, 'w390')
})

test('[F:frontend.src.components.chat.ChatComposer] ChatComposer focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"complementary","name":"Assistant chat"},{"kind":"role","role":"textbox"},{"kind":"role","role":"button","name":"Attach file"}] }, 'focus')
})
