// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.chat.SessionFiles",
  "route": "/",
  "setup": [
    {
      "click": {
        "kind": "role",
        "role": "button",
        "name": "Ask Karbot"
      }
    }
  ],
  "primary": "artifacts"
}

test('[F:frontend.src.components.chat.SessionFiles] SessionFiles empty', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"text","text":"No files yet. Files Karbot or subagents create appear here."}] }, 'empty')
})

test('[F:frontend.src.components.chat.SessionFiles] SessionFiles typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"complementary","name":"Assistant chat"},{"kind":"css","css":"[aria-label=\"Session files\"]"}] }, 'typical')
})

test('[F:frontend.src.components.chat.SessionFiles] SessionFiles dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"complementary","name":"Assistant chat"},{"kind":"css","css":"[aria-label=\"Session files\"]"}] }, 'dark')
})

test('[F:frontend.src.components.chat.SessionFiles] SessionFiles w390', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"complementary","name":"Assistant chat"},{"kind":"css","css":"[aria-label=\"Session files\"]"}] }, 'w390')
})

test('[F:frontend.src.components.chat.SessionFiles] SessionFiles focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"complementary","name":"Assistant chat"},{"kind":"css","css":"[aria-label=\"Session files\"]"}] }, 'focus')
})
