// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.chat.FilesMenu",
  "route": "/",
  "setup": [
    {
      "click": {
        "kind": "role",
        "role": "button",
        "name": "Ask Karbot"
      }
    },
    {
      "click": {
        "kind": "role",
        "role": "button",
        "name": "Attach file"
      }
    }
  ],
  "postAnchors": [
    {
      "kind": "role",
      "role": "menu"
    }
  ],
  "primary": "artifacts"
}

test('[F:frontend.src.components.chat.FilesMenu] FilesMenu typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"textbox"}] }, 'typical')
})

test('[F:frontend.src.components.chat.FilesMenu] FilesMenu dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"textbox"}] }, 'dark')
})

test('[F:frontend.src.components.chat.FilesMenu] FilesMenu w390', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"textbox"}] }, 'w390')
})

test('[F:frontend.src.components.chat.FilesMenu] FilesMenu focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"textbox"}] }, 'focus')
})
