// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.chat.ConversationEmpty",
  "route": "/",
  "setup": [
    {
      "click": {
        "kind": "role",
        "role": "button",
        "name": "Ask Karbot"
      }
    }
  ],
  "primary": "messages",
  "envBasis": "empty"
}

test('[F:frontend.src.components.chat.ConversationEmpty] ConversationEmpty empty', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"text","text":"Ask Karbot anything"}] }, 'empty')
})

test('[F:frontend.src.components.chat.ConversationEmpty] ConversationEmpty dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"complementary","name":"Assistant chat"},{"kind":"text","text":"Ask Karbot anything"},{"kind":"text","text":"Karbot sees every sector you can open."}] }, 'dark')
})

test('[F:frontend.src.components.chat.ConversationEmpty] ConversationEmpty w390', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"complementary","name":"Assistant chat"},{"kind":"text","text":"Ask Karbot anything"},{"kind":"text","text":"Karbot sees every sector you can open."}] }, 'w390')
})

test('[F:frontend.src.components.chat.ConversationEmpty] ConversationEmpty focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"complementary","name":"Assistant chat"},{"kind":"text","text":"Ask Karbot anything"},{"kind":"text","text":"Karbot sees every sector you can open."}] }, 'focus')
})
