// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.chat.ChatStates",
  "route": "/",
  "setup": [
    {
      "click": {
        "kind": "role",
        "role": "button",
        "name": "Ask Karbot"
      }
    }
  ],
  "primary": "sessions"
}

test('[F:frontend.src.components.chat.ChatStates] ChatStates loading', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"status"}] }, 'loading')
})

test('[F:frontend.src.components.chat.ChatStates] ChatStates typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"complementary","name":"Assistant chat"}] }, 'typical')
})

test('[F:frontend.src.components.chat.ChatStates] ChatStates error', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"alert"},{"kind":"role","role":"button","name":"Try again"}] }, 'error')
})

test('[F:frontend.src.components.chat.ChatStates] ChatStates offline', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"text","text":"No connection"},{"kind":"role","role":"button","name":"Try again"}] }, 'offline')
})

test('[F:frontend.src.components.chat.ChatStates] ChatStates dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"complementary","name":"Assistant chat"}] }, 'dark')
})

test('[F:frontend.src.components.chat.ChatStates] ChatStates focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"complementary","name":"Assistant chat"}] }, 'focus')
})
