// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.CommandPalette",
  "route": "/",
  "setup": [
    {
      "press": "Control+k"
    }
  ],
  "postAnchors": [
    {
      "kind": "text",
      "text": "New sector"
    }
  ],
  "primary": "sectors"
}

test('[F:frontend.src.components.CommandPalette] CommandPalette typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"dialog"}] }, 'typical')
})

test('[F:frontend.src.components.CommandPalette] CommandPalette dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"dialog"}] }, 'dark')
})

test('[F:frontend.src.components.CommandPalette] CommandPalette w390', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"dialog"}] }, 'w390')
})

test('[F:frontend.src.components.CommandPalette] CommandPalette focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"dialog"}] }, 'focus')
})
