// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'
import { longtextSnippets } from '../support/factory'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.CompaniesSection",
  "route": "/?section=SectorDetail&sector=sector-matrix",
  "primary": "companies"
}

test('[F:frontend.src.components.CompaniesSection] CompaniesSection loading', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"status"}] }, 'loading')
})

test('[F:frontend.src.components.CompaniesSection] CompaniesSection empty', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"text","text":"No companies yet"}] }, 'empty')
})

test('[F:frontend.src.components.CompaniesSection] CompaniesSection one', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Companies"}], expectedRows: { selector: "table[aria-label=\"Companies\"] [data-list-row]", count: 1 }, expectedTexts: [{ text: "Showing 1 of 1", exact: true }] }, 'one')
})

test('[F:frontend.src.components.CompaniesSection] CompaniesSection typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Companies"}], expectedRows: { selector: "table[aria-label=\"Companies\"] [data-list-row]", count: 8 }, expectedTexts: [{ text: "Showing 8 of 8", exact: true }] }, 'typical')
})

test('[F:frontend.src.components.CompaniesSection] CompaniesSection n100', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Companies"}], expectedRows: { selector: "table[aria-label=\"Companies\"] [data-list-row]", count: 100 }, expectedTexts: [{ text: "Showing 100 of 100", exact: true }] }, 'n100')
})

test('[F:frontend.src.components.CompaniesSection] CompaniesSection n1000', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Companies"}], expectedRows: { selector: "table[aria-label=\"Companies\"] [data-list-row]", count: 100 }, expectedTexts: [{ text: "Showing 100 of 1,000", exact: true }] }, 'n1000')
})

test('[F:frontend.src.components.CompaniesSection] CompaniesSection error', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"alert"},{"kind":"role","role":"button","name":"Try again"}] }, 'error')
})

test('[F:frontend.src.components.CompaniesSection] CompaniesSection denied', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"alert"},{"kind":"text","text":"Ask an owner for access, then try again."},{"kind":"role","role":"button","name":"Try again"}] }, 'denied')
})

test('[F:frontend.src.components.CompaniesSection] CompaniesSection offline', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"text","text":"No connection. Reconnect and try again."},{"kind":"role","role":"button","name":"Try again"}] }, 'offline')
})

test('[F:frontend.src.components.CompaniesSection] CompaniesSection longtext', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Companies"}], expectedRows: { selector: "table[aria-label=\"Companies\"] [data-list-row]", count: 1 }, expectedTexts: [{ text: "Showing 1 of 1", exact: true }, ...longtextSnippets("companies")] }, 'longtext')
})

test('[F:frontend.src.components.CompaniesSection] CompaniesSection dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Companies"}] }, 'dark')
})

test('[F:frontend.src.components.CompaniesSection] CompaniesSection w1280', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Companies"}] }, 'w1280')
})

test('[F:frontend.src.components.CompaniesSection] CompaniesSection w768', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Companies"}] }, 'w768')
})

test('[F:frontend.src.components.CompaniesSection] CompaniesSection w390', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Companies"}] }, 'w390')
})

test('[F:frontend.src.components.CompaniesSection] CompaniesSection focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Companies"}] }, 'focus')
})

test('[F:frontend.src.components.CompaniesSection] CompaniesSection reduced-motion', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Companies"}] }, 'reduced-motion')
})
