// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.CreateSectorDialog",
  "route": "/?section=Researches",
  "setup": [
    {
      "click": {
        "kind": "role",
        "role": "button",
        "name": "New sector"
      }
    }
  ],
  "postAnchors": [
    {
      "kind": "role",
      "role": "dialog",
      "name": "Create a sector"
    }
  ],
  "primary": "sectors"
}

test('[F:frontend.src.components.CreateSectorDialog] CreateSectorDialog typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"button","name":"New sector"}] }, 'typical')
})

test('[F:frontend.src.components.CreateSectorDialog] CreateSectorDialog dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"button","name":"New sector"}] }, 'dark')
})

test('[F:frontend.src.components.CreateSectorDialog] CreateSectorDialog w390', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"button","name":"New sector"}] }, 'w390')
})

test('[F:frontend.src.components.CreateSectorDialog] CreateSectorDialog focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"button","name":"New sector"}] }, 'focus')
})
