// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.Dashboard",
  "route": "/",
  "primary": "sectors",
  "secondary": "companies"
}

test('[F:frontend.src.components.Dashboard] Dashboard loading', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"status"}] }, 'loading')
})

test('[F:frontend.src.components.Dashboard] Dashboard empty', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"text","text":"No sectors yet"}] }, 'empty')
})

test('[F:frontend.src.components.Dashboard] Dashboard typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Overview"},{"kind":"css","css":"[aria-label=\"Recent sectors\"]"}] }, 'typical')
})

test('[F:frontend.src.components.Dashboard] Dashboard error', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"alert"},{"kind":"role","role":"button","name":"Try again"}] }, 'error')
})

test('[F:frontend.src.components.Dashboard] Dashboard denied', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"alert"},{"kind":"text","text":"Ask an owner for access, then try again."}] }, 'denied')
})

test('[F:frontend.src.components.Dashboard] Dashboard offline', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"text","text":"No connection. Reconnect and try again."},{"kind":"role","role":"button","name":"Try again"}] }, 'offline')
})

test('[F:frontend.src.components.Dashboard] Dashboard partial', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Overview"},{"kind":"css","css":"[aria-label=\"Recent sectors\"]"}] }, 'partial')
})

test('[F:frontend.src.components.Dashboard] Dashboard longtext', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Overview"},{"kind":"css","css":"[aria-label=\"Recent sectors\"]"}] }, 'longtext')
})

test('[F:frontend.src.components.Dashboard] Dashboard dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Overview"},{"kind":"css","css":"[aria-label=\"Recent sectors\"]"}] }, 'dark')
})

test('[F:frontend.src.components.Dashboard] Dashboard w1280', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Overview"},{"kind":"css","css":"[aria-label=\"Recent sectors\"]"}] }, 'w1280')
})

test('[F:frontend.src.components.Dashboard] Dashboard w768', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Overview"},{"kind":"css","css":"[aria-label=\"Recent sectors\"]"}] }, 'w768')
})

test('[F:frontend.src.components.Dashboard] Dashboard w390', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Overview"},{"kind":"css","css":"[aria-label=\"Recent sectors\"]"}] }, 'w390')
})

test('[F:frontend.src.components.Dashboard] Dashboard reduced-motion', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Overview"},{"kind":"css","css":"[aria-label=\"Recent sectors\"]"}] }, 'reduced-motion')
})
