// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.ExecutionInspector",
  "route": "/?section=SectorChat&sector=sector-matrix&session=mx-session-001&thread=mx-session-001",
  "setup": [
    {
      "click": {
        "kind": "role",
        "role": "button",
        "name": "Conversation options"
      }
    },
    {
      "click": {
        "kind": "role",
        "role": "menuitem",
        "name": "Execution records"
      }
    }
  ],
  "postAnchors": [
    {
      "kind": "role",
      "role": "dialog",
      "name": "Execution records"
    }
  ],
  "primary": "execution"
}

test('[F:frontend.src.components.ExecutionInspector] ExecutionInspector loading', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"status"}] }, 'loading')
})

test('[F:frontend.src.components.ExecutionInspector] ExecutionInspector typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"button","name":"Conversation options"}] }, 'typical')
})

test('[F:frontend.src.components.ExecutionInspector] ExecutionInspector error', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"alert"},{"kind":"role","role":"button","name":"Try again"}] }, 'error')
})

test('[F:frontend.src.components.ExecutionInspector] ExecutionInspector denied', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"alert"},{"kind":"text","text":"Ask an owner for access, then try again."}] }, 'denied')
})

test('[F:frontend.src.components.ExecutionInspector] ExecutionInspector offline', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"text","text":"No connection. Reconnect and try again."},{"kind":"role","role":"button","name":"Try again"}] }, 'offline')
})

test('[F:frontend.src.components.ExecutionInspector] ExecutionInspector dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"button","name":"Conversation options"}] }, 'dark')
})

test('[F:frontend.src.components.ExecutionInspector] ExecutionInspector w390', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"button","name":"Conversation options"}] }, 'w390')
})

test('[F:frontend.src.components.ExecutionInspector] ExecutionInspector focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"button","name":"Conversation options"}] }, 'focus')
})
