// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.FileTypeIcon",
  "route": "/?section=SectorChat&sector=sector-matrix&session=mx-session-001&thread=mx-session-001",
  "primary": "files"
}

test('[F:frontend.src.components.FileTypeIcon] FileTypeIcon typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[aria-label=\"Sector files\"]"}] }, 'typical')
})

test('[F:frontend.src.components.FileTypeIcon] FileTypeIcon dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[aria-label=\"Sector files\"]"}] }, 'dark')
})
