// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.local_context_editor",
  "route": "/?section=SectorChat&sector=sector-matrix&session=mx-session-001&thread=mx-session-001",
  "gated": true,
  "setup": [
    {
      "click": {
        "kind": "role",
        "role": "button",
        "name": "Conversation options"
      }
    },
    {
      "click": {
        "kind": "role",
        "role": "menuitem",
        "name": "Local context"
      }
    }
  ],
  "postAnchors": [
    {
      "kind": "text",
      "text": "Local context"
    }
  ],
  "primary": "local"
}

test('[F:frontend.src.components.local_context_editor] local_context_editor typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"button","name":"Conversation options"}] }, 'typical')
})

test('[F:frontend.src.components.local_context_editor] local_context_editor error', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"button","name":"Conversation options"}], postAnchors: [{"kind":"text","text":"Local context"},{"kind":"role","role":"alert"},{"kind":"role","role":"button","name":"Try again"}] }, 'error')
})

test('[F:frontend.src.components.local_context_editor] local_context_editor denied', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"button","name":"Conversation options"}], postAnchors: [{"kind":"text","text":"Local context"},{"kind":"role","role":"alert"},{"kind":"text","text":"Ask an owner for access, then try again."}] }, 'denied')
})

test('[F:frontend.src.components.local_context_editor] local_context_editor offline', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"button","name":"Conversation options"}], postAnchors: [{"kind":"text","text":"Local context"},{"kind":"text","text":"No connection. Reconnect and try again."},{"kind":"role","role":"button","name":"Try again"}] }, 'offline')
})

test('[F:frontend.src.components.local_context_editor] local_context_editor dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"button","name":"Conversation options"}] }, 'dark')
})

test('[F:frontend.src.components.local_context_editor] local_context_editor w390', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"button","name":"Conversation options"}] }, 'w390')
})

test('[F:frontend.src.components.local_context_editor] local_context_editor focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"button","name":"Conversation options"}] }, 'focus')
})
