// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.Markdown",
  "route": "/?section=SectorChat&sector=sector-matrix&session=mx-session-001&thread=mx-session-001",
  "primary": "messages"
}

test('[F:frontend.src.components.Markdown] Markdown typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[aria-label=\"Conversation messages\"]"},{"kind":"css","css":"[aria-label=\"Conversation messages\"] table"}] }, 'typical')
})

test('[F:frontend.src.components.Markdown] Markdown longtext', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[aria-label=\"Conversation messages\"]"},{"kind":"css","css":"[aria-label=\"Conversation messages\"] table"}] }, 'longtext')
})

test('[F:frontend.src.components.Markdown] Markdown dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[aria-label=\"Conversation messages\"]"},{"kind":"css","css":"[aria-label=\"Conversation messages\"] table"}] }, 'dark')
})

test('[F:frontend.src.components.Markdown] Markdown w390', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[aria-label=\"Conversation messages\"]"},{"kind":"css","css":"[aria-label=\"Conversation messages\"] table"}] }, 'w390')
})
