// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.ModelToolbar",
  "route": "/?section=SectorChat&sector=sector-matrix&session=mx-session-001&thread=mx-session-001",
  "primary": "sessions"
}

test('[F:frontend.src.components.ModelToolbar] ModelToolbar typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[aria-label=\"Choose a model\"]"}] }, 'typical')
})

test('[F:frontend.src.components.ModelToolbar] ModelToolbar error', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"alert"},{"kind":"role","role":"button","name":"Try again"}] }, 'error')
})

test('[F:frontend.src.components.ModelToolbar] ModelToolbar dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[aria-label=\"Choose a model\"]"}] }, 'dark')
})

test('[F:frontend.src.components.ModelToolbar] ModelToolbar w390', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[aria-label=\"Choose a model\"]"}] }, 'w390')
})

test('[F:frontend.src.components.ModelToolbar] ModelToolbar focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[aria-label=\"Choose a model\"]"}] }, 'focus')
})
