// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.ModelsPanel",
  "route": "/?section=Models",
  "primary": "sessions",
  "secondary": "providers"
}

test('[F:frontend.src.components.ModelsPanel] ModelsPanel loading', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"status"}] }, 'loading')
})

test('[F:frontend.src.components.ModelsPanel] ModelsPanel empty', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"text","text":"No sessions yet. Start one from chat to bind a model."}] }, 'empty')
})

test('[F:frontend.src.components.ModelsPanel] ModelsPanel typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Models"}] }, 'typical')
})

test('[F:frontend.src.components.ModelsPanel] ModelsPanel error', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"alert"},{"kind":"role","role":"button","name":"Try again"}] }, 'error')
})

test('[F:frontend.src.components.ModelsPanel] ModelsPanel denied', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"text","text":"Ask an owner for access, then try again."}] }, 'denied')
})

test('[F:frontend.src.components.ModelsPanel] ModelsPanel offline', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"text","text":"No connection"},{"kind":"role","role":"button","name":"Try again"}] }, 'offline')
})

test('[F:frontend.src.components.ModelsPanel] ModelsPanel partial', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Models"}] }, 'partial')
})

test('[F:frontend.src.components.ModelsPanel] ModelsPanel dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Models"}] }, 'dark')
})

test('[F:frontend.src.components.ModelsPanel] ModelsPanel w1280', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Models"}] }, 'w1280')
})

test('[F:frontend.src.components.ModelsPanel] ModelsPanel w768', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Models"}] }, 'w768')
})

test('[F:frontend.src.components.ModelsPanel] ModelsPanel w390', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Models"}] }, 'w390')
})

test('[F:frontend.src.components.ModelsPanel] ModelsPanel focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Models"}] }, 'focus')
})
