// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.plan.PlanSteps",
  "route": "/?section=SectorChat&sector=sector-matrix&session=session-sector-matrix-research&thread=session-sector-matrix-research",
  "setup": [
    {
      "click": {
        "kind": "role",
        "role": "tab",
        "name": "Plan"
      }
    }
  ],
  "primary": "plan"
}

test('[F:frontend.src.components.plan.PlanSteps] PlanSteps loading', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"tab","name":"Plan"}] }, 'loading')
})

test('[F:frontend.src.components.plan.PlanSteps] PlanSteps typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"tab","name":"Plan"}] }, 'typical')
})

test('[F:frontend.src.components.plan.PlanSteps] PlanSteps dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"tab","name":"Plan"}] }, 'dark')
})

test('[F:frontend.src.components.plan.PlanSteps] PlanSteps w390', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"tab","name":"Plan"}] }, 'w390')
})

test('[F:frontend.src.components.plan.PlanSteps] PlanSteps focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"tab","name":"Plan"}] }, 'focus')
})
