// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.research_parts",
  "route": "/?section=Researches",
  "primary": "sectors"
}

test('[F:frontend.src.components.research_parts] research_parts typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Researches"}], expectedRows: { selector: "table[aria-label=\"Sectors\"] [data-list-row]", count: 8 } }, 'typical')
})

test('[F:frontend.src.components.research_parts] research_parts n100', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Researches"}], expectedRows: { selector: "table[aria-label=\"Sectors\"] [data-list-row]", count: 50 }, expectedTexts: [{ text: "Showing 50 of 100", exact: true }] }, 'n100')
})

test('[F:frontend.src.components.research_parts] research_parts dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Researches"}] }, 'dark')
})

test('[F:frontend.src.components.research_parts] research_parts w390', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Researches"}] }, 'w390')
})
