// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.ResearchesPage",
  "route": "/?section=Researches",
  "primary": "sectors",
  "secondary": "companies"
}

test('[F:frontend.src.components.ResearchesPage] ResearchesPage loading', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"status"}] }, 'loading')
})

test('[F:frontend.src.components.ResearchesPage] ResearchesPage empty', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"text","text":"No sectors yet"}] }, 'empty')
})

test('[F:frontend.src.components.ResearchesPage] ResearchesPage typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Researches"}] }, 'typical')
})

test('[F:frontend.src.components.ResearchesPage] ResearchesPage n100', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Researches"}] }, 'n100')
})

test('[F:frontend.src.components.ResearchesPage] ResearchesPage n1000', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Researches"}] }, 'n1000')
})

test('[F:frontend.src.components.ResearchesPage] ResearchesPage error', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"alert"},{"kind":"role","role":"button","name":"Try again"}] }, 'error')
})

test('[F:frontend.src.components.ResearchesPage] ResearchesPage denied', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"alert"},{"kind":"text","text":"Ask an owner for access, then try again."}] }, 'denied')
})

test('[F:frontend.src.components.ResearchesPage] ResearchesPage offline', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"text","text":"No connection. Reconnect and try again."},{"kind":"role","role":"button","name":"Try again"}] }, 'offline')
})

test('[F:frontend.src.components.ResearchesPage] ResearchesPage partial', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Researches"}] }, 'partial')
})

test('[F:frontend.src.components.ResearchesPage] ResearchesPage longtext', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Researches"}] }, 'longtext')
})

test('[F:frontend.src.components.ResearchesPage] ResearchesPage dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Researches"}] }, 'dark')
})

test('[F:frontend.src.components.ResearchesPage] ResearchesPage w1280', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Researches"}] }, 'w1280')
})

test('[F:frontend.src.components.ResearchesPage] ResearchesPage w768', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Researches"}] }, 'w768')
})

test('[F:frontend.src.components.ResearchesPage] ResearchesPage w390', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Researches"}] }, 'w390')
})

test('[F:frontend.src.components.ResearchesPage] ResearchesPage reduced-motion', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Researches"}] }, 'reduced-motion')
})
