// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.ResearchPlanEditor",
  "route": "/?section=SectorChat&sector=sector-matrix&session=mx-session-001&thread=mx-session-001",
  "setup": [
    {
      "click": {
        "kind": "css",
        "css": "[data-tab-value=\"plan\"]"
      }
    }
  ],
  "primary": "plan"
}

test('[F:frontend.src.components.ResearchPlanEditor] ResearchPlanEditor typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[data-tab-value=\"plan\"]"},{"kind":"css","css":"[aria-label=\"Plan text\"]"}] }, 'typical')
})

test('[F:frontend.src.components.ResearchPlanEditor] ResearchPlanEditor dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[data-tab-value=\"plan\"]"},{"kind":"css","css":"[aria-label=\"Plan text\"]"}] }, 'dark')
})

test('[F:frontend.src.components.ResearchPlanEditor] ResearchPlanEditor w390', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[data-tab-value=\"plan\"]"},{"kind":"css","css":"[aria-label=\"Plan text\"]"}] }, 'w390')
})

test('[F:frontend.src.components.ResearchPlanEditor] ResearchPlanEditor focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[data-tab-value=\"plan\"]"},{"kind":"css","css":"[aria-label=\"Plan text\"]"}] }, 'focus')
})
