// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.RunsPanel",
  "route": "/?section=Agents",
  "primary": "runs"
}

test('[F:frontend.src.components.RunsPanel] RunsPanel loading', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"status"}] }, 'loading')
})

test('[F:frontend.src.components.RunsPanel] RunsPanel empty', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"text","text":"No runs yet"}] }, 'empty')
})

test('[F:frontend.src.components.RunsPanel] RunsPanel one', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Runs"}], expectedRows: { selector: "table[aria-label=\"Agent runs\"] [data-list-row]", count: 1 } }, 'one')
})

test('[F:frontend.src.components.RunsPanel] RunsPanel typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Runs"}], expectedRows: { selector: "table[aria-label=\"Agent runs\"] [data-list-row]", count: 8 } }, 'typical')
})

test('[F:frontend.src.components.RunsPanel] RunsPanel error', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"alert"},{"kind":"role","role":"button","name":"Try again"}] }, 'error')
})

test('[F:frontend.src.components.RunsPanel] RunsPanel denied', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"text","text":"Ask an owner for access, then try again."},{"kind":"role","role":"button","name":"Try again"}] }, 'denied')
})

test('[F:frontend.src.components.RunsPanel] RunsPanel offline', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"text","text":"No connection"},{"kind":"role","role":"button","name":"Try again"}] }, 'offline')
})

test('[F:frontend.src.components.RunsPanel] RunsPanel dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Runs"}] }, 'dark')
})

test('[F:frontend.src.components.RunsPanel] RunsPanel w1280', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Runs"}] }, 'w1280')
})

test('[F:frontend.src.components.RunsPanel] RunsPanel w768', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Runs"}] }, 'w768')
})

test('[F:frontend.src.components.RunsPanel] RunsPanel w390', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Runs"}] }, 'w390')
})

test('[F:frontend.src.components.RunsPanel] RunsPanel focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Runs"}] }, 'focus')
})

test('[F:frontend.src.components.RunsPanel] RunsPanel reduced-motion', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Runs"}] }, 'reduced-motion')
})
