// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'
import { longtextSnippets } from '../support/factory'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.SectorLanding",
  "route": "/?section=SectorDetail&sector=sector-matrix",
  "primary": "sector"
}

test('[F:frontend.src.components.SectorLanding] SectorLanding loading', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"status"}] }, 'loading')
})

test('[F:frontend.src.components.SectorLanding] SectorLanding empty', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"text","text":"Sector not found"}] }, 'empty')
})

test('[F:frontend.src.components.SectorLanding] SectorLanding typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Research status"},{"kind":"role","role":"button","name":"Open workspace"}] }, 'typical')
})

test('[F:frontend.src.components.SectorLanding] SectorLanding error', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"alert"},{"kind":"role","role":"button","name":"Try again"}] }, 'error')
})

test('[F:frontend.src.components.SectorLanding] SectorLanding denied', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"alert"},{"kind":"text","text":"Ask an owner for access, then try again."},{"kind":"role","role":"button","name":"Try again"}] }, 'denied')
})

test('[F:frontend.src.components.SectorLanding] SectorLanding offline', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"text","text":"No connection. Reconnect and try again."},{"kind":"role","role":"button","name":"Try again"}] }, 'offline')
})

test('[F:frontend.src.components.SectorLanding] SectorLanding longtext', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Research status"},{"kind":"role","role":"button","name":"Open workspace"}], expectedTexts: [...longtextSnippets("sector")] }, 'longtext')
})

test('[F:frontend.src.components.SectorLanding] SectorLanding dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Research status"},{"kind":"role","role":"button","name":"Open workspace"}] }, 'dark')
})

test('[F:frontend.src.components.SectorLanding] SectorLanding w1280', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Research status"},{"kind":"role","role":"button","name":"Open workspace"}] }, 'w1280')
})

test('[F:frontend.src.components.SectorLanding] SectorLanding w768', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Research status"},{"kind":"role","role":"button","name":"Open workspace"}] }, 'w768')
})

test('[F:frontend.src.components.SectorLanding] SectorLanding w390', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Research status"},{"kind":"role","role":"button","name":"Open workspace"}] }, 'w390')
})

test('[F:frontend.src.components.SectorLanding] SectorLanding focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Research status"},{"kind":"role","role":"button","name":"Open workspace"}] }, 'focus')
})

test('[F:frontend.src.components.SectorLanding] SectorLanding reduced-motion', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Research status"},{"kind":"role","role":"button","name":"Open workspace"}] }, 'reduced-motion')
})
