// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.SectorFilePreview",
  "route": "/?section=SectorChat&sector=sector-matrix&session=mx-session-001&thread=mx-session-001",
  "gated": true,
  "setup": [
    {
      "click": {
        "kind": "text",
        "text": "parramatta-crew-notes.md"
      }
    }
  ],
  "postAnchors": [
    {
      "kind": "text",
      "text": "File preview"
    }
  ],
  "primary": "fileBody"
}

test('[F:frontend.src.components.SectorFilePreview] SectorFilePreview loading', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[aria-label=\"Sector files\"]"}], postAnchors: [{"kind":"text","text":"File preview"},{"kind":"role","role":"status"}] }, 'loading')
})

test('[F:frontend.src.components.SectorFilePreview] SectorFilePreview typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[aria-label=\"Sector files\"]"}] }, 'typical')
})

test('[F:frontend.src.components.SectorFilePreview] SectorFilePreview error', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[aria-label=\"Sector files\"]"}], postAnchors: [{"kind":"text","text":"File preview"},{"kind":"role","role":"alert"},{"kind":"role","role":"button","name":"Try again"}] }, 'error')
})

test('[F:frontend.src.components.SectorFilePreview] SectorFilePreview denied', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[aria-label=\"Sector files\"]"}], postAnchors: [{"kind":"text","text":"File preview"},{"kind":"role","role":"alert"},{"kind":"text","text":"Ask an owner for access, then try again."},{"kind":"role","role":"button","name":"Try again"}] }, 'denied')
})

test('[F:frontend.src.components.SectorFilePreview] SectorFilePreview offline', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[aria-label=\"Sector files\"]"}], postAnchors: [{"kind":"text","text":"File preview"},{"kind":"text","text":"No connection. Reconnect and try again."},{"kind":"role","role":"button","name":"Try again"}] }, 'offline')
})

test('[F:frontend.src.components.SectorFilePreview] SectorFilePreview dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[aria-label=\"Sector files\"]"}] }, 'dark')
})

test('[F:frontend.src.components.SectorFilePreview] SectorFilePreview w390', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[aria-label=\"Sector files\"]"}] }, 'w390')
})
