// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'
import { longtextSnippets } from '../support/factory'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.SectorWorkspace",
  "route": "/?section=SectorChat&sector=sector-matrix&session=mx-session-001&thread=mx-session-001",
  "primary": "sessions",
  "secondary": "messages"
}

test('[F:frontend.src.components.SectorWorkspace] SectorWorkspace loading', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"status"}] }, 'loading')
})

test('[F:frontend.src.components.SectorWorkspace] SectorWorkspace empty', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"text","text":"No chats yet"}] }, 'empty')
})

test('[F:frontend.src.components.SectorWorkspace] SectorWorkspace typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"log","name":"Conversation messages"}], expectedRows: { selector: "[aria-label=\"Chat sessions\"] [data-list-row]", count: 12 } }, 'typical')
})

test('[F:frontend.src.components.SectorWorkspace] SectorWorkspace error', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"alert"},{"kind":"role","role":"button","name":"Try again"}] }, 'error')
})

test('[F:frontend.src.components.SectorWorkspace] SectorWorkspace denied', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"alert"},{"kind":"text","text":"Ask an owner for access, then try again."}] }, 'denied')
})

test('[F:frontend.src.components.SectorWorkspace] SectorWorkspace offline', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"text","text":"No connection. Reconnect and try again."},{"kind":"role","role":"button","name":"Try again"}] }, 'offline')
})

test('[F:frontend.src.components.SectorWorkspace] SectorWorkspace partial', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"log","name":"Conversation messages"}], expectedRows: { selector: "[aria-label=\"Chat sessions\"] [data-list-row]", count: 9 } }, 'partial')
})

test('[F:frontend.src.components.SectorWorkspace] SectorWorkspace longtext', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"log","name":"Conversation messages"}], expectedRows: { selector: "[aria-label=\"Chat sessions\"] [data-list-row]", count: 9 }, expectedTexts: [...longtextSnippets("sessions")] }, 'longtext')
})

test('[F:frontend.src.components.SectorWorkspace] SectorWorkspace dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"log","name":"Conversation messages"}] }, 'dark')
})

test('[F:frontend.src.components.SectorWorkspace] SectorWorkspace w1280', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"log","name":"Conversation messages"}] }, 'w1280')
})

test('[F:frontend.src.components.SectorWorkspace] SectorWorkspace w768', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"log","name":"Conversation messages"}] }, 'w768')
})

test('[F:frontend.src.components.SectorWorkspace] SectorWorkspace w390', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"log","name":"Conversation messages"}] }, 'w390')
})

test('[F:frontend.src.components.SectorWorkspace] SectorWorkspace focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"log","name":"Conversation messages"}] }, 'focus')
})

test('[F:frontend.src.components.SectorWorkspace] SectorWorkspace reduced-motion', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"log","name":"Conversation messages"}] }, 'reduced-motion')
})
