// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.Sidebar",
  "route": "/",
  "primary": "sectors"
}

test('[F:frontend.src.components.Sidebar] Sidebar typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"navigation","name":"Primary"}] }, 'typical')
})

test('[F:frontend.src.components.Sidebar] Sidebar dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"navigation","name":"Primary"}] }, 'dark')
})

test('[F:frontend.src.components.Sidebar] Sidebar w1280', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"navigation","name":"Primary"}] }, 'w1280')
})

test('[F:frontend.src.components.Sidebar] Sidebar w768', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"navigation","name":"Primary"}] }, 'w768')
})

test('[F:frontend.src.components.Sidebar] Sidebar w390', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"navigation","name":"Primary"}] }, 'w390')
})

test('[F:frontend.src.components.Sidebar] Sidebar focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"navigation","name":"Primary"}] }, 'focus')
})

test('[F:frontend.src.components.Sidebar] Sidebar reduced-motion', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"navigation","name":"Primary"}] }, 'reduced-motion')
})
