// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.StatusPill",
  "route": "/?section=Agents",
  "primary": "runs"
}

test('[F:frontend.src.components.StatusPill] StatusPill typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Runs"},{"kind":"css","css":"[data-tone]"}] }, 'typical')
})

test('[F:frontend.src.components.StatusPill] StatusPill dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Runs"},{"kind":"css","css":"[data-tone]"}] }, 'dark')
})
