// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.SupervisionAlertsPanel",
  "route": "/?section=Agents",
  "primary": "alerts"
}

test('[F:frontend.src.components.SupervisionAlertsPanel] SupervisionAlertsPanel loading', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"status"}] }, 'loading')
})

test('[F:frontend.src.components.SupervisionAlertsPanel] SupervisionAlertsPanel empty', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"text","text":"All clear"}] }, 'empty')
})

test('[F:frontend.src.components.SupervisionAlertsPanel] SupervisionAlertsPanel typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Alerts"}] }, 'typical')
})

test('[F:frontend.src.components.SupervisionAlertsPanel] SupervisionAlertsPanel error', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"alert"},{"kind":"role","role":"button","name":"Try again"}] }, 'error')
})

test('[F:frontend.src.components.SupervisionAlertsPanel] SupervisionAlertsPanel denied', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"alert"},{"kind":"text","text":"Ask an owner for access, then try again."},{"kind":"role","role":"button","name":"Try again"}] }, 'denied')
})

test('[F:frontend.src.components.SupervisionAlertsPanel] SupervisionAlertsPanel offline', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"text","text":"No connection. Reconnect and try again."},{"kind":"role","role":"button","name":"Try again"}] }, 'offline')
})

test('[F:frontend.src.components.SupervisionAlertsPanel] SupervisionAlertsPanel dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Alerts"}] }, 'dark')
})

test('[F:frontend.src.components.SupervisionAlertsPanel] SupervisionAlertsPanel w390', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Alerts"}] }, 'w390')
})

test('[F:frontend.src.components.SupervisionAlertsPanel] SupervisionAlertsPanel focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Alerts"}] }, 'focus')
})
