// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.ThemeMenu",
  "route": "/",
  "setup": [
    {
      "click": {
        "kind": "role",
        "role": "button",
        "name": "Theme"
      }
    }
  ],
  "postAnchors": [
    {
      "kind": "role",
      "role": "menuitemradio",
      "name": "Dark"
    }
  ],
  "primary": "sectors"
}

test('[F:frontend.src.components.ThemeMenu] ThemeMenu typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"button","name":"Theme"}] }, 'typical')
})

test('[F:frontend.src.components.ThemeMenu] ThemeMenu dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"button","name":"Theme"}] }, 'dark')
})

test('[F:frontend.src.components.ThemeMenu] ThemeMenu focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"button","name":"Theme"}] }, 'focus')
})
