// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.ui.alert_dialog",
  "route": "/?section=Agents",
  "setup": [
    {
      "click": {
        "kind": "role",
        "role": "button",
        "name": "Cancel"
      }
    }
  ],
  "postAnchors": [
    {
      "kind": "text",
      "text": "Cancel this run?"
    },
    {
      "kind": "role",
      "role": "button",
      "name": "Cancel run"
    }
  ],
  "primary": "runs"
}

test('[F:frontend.src.components.ui.alert_dialog] alert_dialog typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Runs"}] }, 'typical')
})

test('[F:frontend.src.components.ui.alert_dialog] alert_dialog dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Runs"}] }, 'dark')
})

test('[F:frontend.src.components.ui.alert_dialog] alert_dialog w390', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Runs"}] }, 'w390')
})

test('[F:frontend.src.components.ui.alert_dialog] alert_dialog focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Runs"}] }, 'focus')
})
