// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.ui.badge",
  "route": "/",
  "primary": "sectors"
}

test('[F:frontend.src.components.ui.badge] badge typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"navigation","name":"Primary"},{"kind":"css","css":"[data-slot=\"badge\"]"}] }, 'typical')
})

test('[F:frontend.src.components.ui.badge] badge dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"navigation","name":"Primary"},{"kind":"css","css":"[data-slot=\"badge\"]"}] }, 'dark')
})
