// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.ui.button",
  "route": "/?section=Researches",
  "focusSubject": {
    "kind": "css",
    "css": "[data-slot=\"button\"]"
  },
  "primary": "sectors"
}

test('[F:frontend.src.components.ui.button] button typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Researches"},{"kind":"css","css":"[data-slot=\"button\"]"}] }, 'typical')
})

test('[F:frontend.src.components.ui.button] button dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Researches"},{"kind":"css","css":"[data-slot=\"button\"]"}] }, 'dark')
})

test('[F:frontend.src.components.ui.button] button focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Researches"},{"kind":"css","css":"[data-slot=\"button\"]"}] }, 'focus')
})
