// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.ui.field",
  "route": "/?section=Models",
  "primary": "sessions"
}

test('[F:frontend.src.components.ui.field] field typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Models"},{"kind":"css","css":"[data-slot=\"field\"]"}] }, 'typical')
})

test('[F:frontend.src.components.ui.field] field dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Models"},{"kind":"css","css":"[data-slot=\"field\"]"}] }, 'dark')
})
