// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.ui.input",
  "route": "/?section=Agents",
  "focusSubject": {
    "kind": "role",
    "role": "textbox",
    "name": "Search runs"
  },
  "primary": "runs"
}

test('[F:frontend.src.components.ui.input] input typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Runs"},{"kind":"role","role":"textbox","name":"Search runs"}] }, 'typical')
})

test('[F:frontend.src.components.ui.input] input dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Runs"},{"kind":"role","role":"textbox","name":"Search runs"}] }, 'dark')
})

test('[F:frontend.src.components.ui.input] input focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Runs"},{"kind":"role","role":"textbox","name":"Search runs"}] }, 'focus')
})
