// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.ui.progress",
  "route": "/?section=SectorChat&sector=sector-matrix&session=session-sector-matrix-research&thread=session-sector-matrix-research",
  "gated": true,
  "setup": [
    {
      "click": {
        "kind": "role",
        "role": "tab",
        "name": "Plan"
      }
    }
  ],
  "postAnchors": [
    {
      "kind": "role",
      "role": "tab",
      "name": "Plan"
    },
    {
      "kind": "css",
      "css": "[data-slot=\"progress\"]"
    }
  ],
  "primary": "progress"
}

test('[F:frontend.src.components.ui.progress] progress typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"tab","name":"Plan"}] }, 'typical')
})

test('[F:frontend.src.components.ui.progress] progress dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"tab","name":"Plan"}] }, 'dark')
})

test('[F:frontend.src.components.ui.progress] progress focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"tab","name":"Plan"}] }, 'focus')
})
