// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.ui.popover",
  "route": "/?section=SectorChat&sector=sector-matrix&session=mx-session-001&thread=mx-session-001",
  "focusSubject": {
    "kind": "css",
    "css": "[data-slot=\"popover-trigger\"]"
  },
  "primary": "global"
}

test('[F:frontend.src.components.ui.popover] popover typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[data-slot=\"popover-trigger\"]"}] }, 'typical')
})

test('[F:frontend.src.components.ui.popover] popover dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[data-slot=\"popover-trigger\"]"}] }, 'dark')
})

test('[F:frontend.src.components.ui.popover] popover focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"css","css":"[data-slot=\"popover-trigger\"]"}] }, 'focus')
})
