// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.ui.switch",
  "route": "/?section=SectorChat&sector=sector-matrix&session=mx-session-001&thread=mx-session-001",
  "setup": [
    {
      "click": {
        "kind": "role",
        "role": "button",
        "name": "Conversation options"
      }
    }
  ],
  "postAnchors": [
    {
      "kind": "css",
      "css": "[data-slot=\"switch\"]"
    }
  ],
  "primary": "sessions"
}

test('[F:frontend.src.components.ui.switch] switch typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"button","name":"Conversation options"}] }, 'typical')
})

test('[F:frontend.src.components.ui.switch] switch dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"button","name":"Conversation options"}] }, 'dark')
})

test('[F:frontend.src.components.ui.switch] switch focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"button","name":"Conversation options"}] }, 'focus')
})
