// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.ui.select",
  "route": "/?section=Researches",
  "setup": [
    {
      "click": {
        "kind": "css",
        "css": "[aria-label=\"Research type\"]"
      }
    }
  ],
  "postAnchors": [
    {
      "kind": "role",
      "role": "option"
    }
  ],
  "focusSubject": {
    "kind": "css",
    "css": "[aria-label=\"Research type\"]"
  },
  "primary": "sectors"
}

test('[F:frontend.src.components.ui.select] select typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Researches"},{"kind":"css","css":"[aria-label=\"Research type\"]"}] }, 'typical')
})

test('[F:frontend.src.components.ui.select] select dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Researches"},{"kind":"css","css":"[aria-label=\"Research type\"]"}] }, 'dark')
})

test('[F:frontend.src.components.ui.select] select focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"heading","name":"Researches"},{"kind":"css","css":"[aria-label=\"Research type\"]"}] }, 'focus')
})
