// GENERATED by npm run matrix:sync from tests/registry/features.yaml (states)
// + tests/frontend-e2e/matrix/components.json. Do not edit.
import { test } from '@playwright/test'
import { runMatrixState, type MatrixCase } from '../support/matrix'

const base: Omit<MatrixCase, 'anchors'> = {
  "id": "frontend.src.components.ui.tabs",
  "route": "/?section=Agents",
  "primary": "alerts"
}

test('[F:frontend.src.components.ui.tabs] tabs typical', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Alerts"},{"kind":"css","css":"[aria-label=\"Alert scope\"]"}] }, 'typical')
})

test('[F:frontend.src.components.ui.tabs] tabs dark', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Alerts"},{"kind":"css","css":"[aria-label=\"Alert scope\"]"}] }, 'dark')
})

test('[F:frontend.src.components.ui.tabs] tabs focus', async ({ page }) => {
  await runMatrixState(page, { ...base, anchors: [{"kind":"role","role":"region","name":"Alerts"},{"kind":"css","css":"[aria-label=\"Alert scope\"]"}] }, 'focus')
})
