import { useEffect, useRef, useState } from 'react'
import { ArrowLeft, ArrowUp, BookOpen, ChevronRight, FolderOpen, GitBranch, Menu, MessageCircle, Moon, MoreHorizontal, Pause, Play, Plus, Search, Square, Sun } from 'lucide-react'
import type { SectorWorkspaceModel } from '../data/sector-workspace'
import type { ResearchState, SectorDetail, StagingConfig } from '../data/staging-api'
import { ActivityGroup, groupMessageSegments, ThinkingPlaceholder } from './ChatPanel'
import { AgentBubble, UserBubble, useChatStick } from './chat-parts'
import { Markdown } from './Markdown'
import { SectorFilePreview } from './SectorFilePreview'
import { ResearchPlanEditor, ExecutablePlanDetails } from './ResearchPlanEditor'
import { ModelToolbar } from './ModelToolbar'
import { stateLabel } from './research-parts'
import { GlobalContextPanel, LocalContextEditor, PlanProgress, ResourceNotice, WorkspaceFiles, WorkspaceOverlay } from './workspace-parts'
import { Button } from './ui/button'
import { Input } from './ui/input'

export interface ResearchActions {
  busy: boolean; error: string | null
  plan(): void; approve(version: number): void; start(): void; pause(): void; resume(): void; edit(markdown: string): Promise<boolean>
}
export function SectorWorkspace({ sector, model, config, actions, dark, onTheme, onBack }: {
  sector: SectorDetail; model: SectorWorkspaceModel; config: StagingConfig; actions: ResearchActions; dark: boolean; onTheme(): void; onBack(): void
}) {
  const [group, setGroup] = useState<'research' | 'normal'>('research')
  const [tab, setTab] = useState<'chat' | 'plan'>('chat')
  const [navOpen, setNavOpen] = useState(false), [resourcesOpen, setResourcesOpen] = useState(false), [contextOpen, setContextOpen] = useState(false), [directory, setDirectory] = useState(false), [options, setOptions] = useState(false)
  const [sessionQuery, setSessionQuery] = useState(''), [sessionLimit, setSessionLimit] = useState(50)
  const selected = model.selected
  const [seenSession, setSeenSession] = useState(selected?.id)
  if (selected && seenSession !== selected.id) { setSeenSession(selected.id); setGroup(selected.kind === 'research' ? 'research' : 'normal') }
  const normal = model.sessions.data?.filter((session) => session.kind !== 'research') ?? []
  const research = model.sessions.data?.find((session) => session.kind === 'research')
  const listed = (group === 'research' ? research ? [research] : [] : normal).filter((session) => session.title.toLowerCase().includes(sessionQuery.toLowerCase()))
  const children = model.threads.data?.filter((thread) => thread.kind === 'subagent') ?? []
  const busy = Boolean(model.operation)
  const sessionRail = <div className="flex h-full min-h-0 flex-col">
    <div className="flex items-center gap-2 px-4 py-5"><Button variant="ghost" size="icon" aria-label="Back to sector summary" onClick={onBack}><ArrowLeft className="size-4" aria-hidden /></Button><span title={sector.name} className="min-w-0 truncate text-sm font-semibold">{sector.name}</span></div>
    <div role="group" aria-label="Session types" className="mx-4 grid grid-cols-2 rounded-lg bg-muted p-1">{(['research','normal'] as const).map((kind) => <button key={kind} type="button" aria-pressed={group === kind} onClick={() => { setGroup(kind); setSessionQuery(''); setSessionLimit(50); const first = kind === 'research' ? research : normal[0]; if (first) model.openSession(first.id) }} className={`cursor-pointer rounded-md px-2 py-2 text-xs font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${group === kind ? 'bg-background text-foreground shadow-sm' : 'text-muted-foreground hover:text-foreground'}`}>{kind === 'research' ? 'Research' : 'Chats'}</button>)}</div>
    <div className="flex items-center justify-between px-5 pt-5 pb-2"><h2 className="text-[11px] font-medium uppercase tracking-wider text-muted-foreground">{group === 'research' ? 'Research session' : 'Conversations'}</h2>{group === 'normal' ? <Button variant="ghost" size="icon-sm" aria-label="New conversation" disabled={busy} onClick={() => void model.createChat()}><Plus className="size-4" aria-hidden /></Button> : null}</div>
    {normal.length > 5 && group === 'normal' ? <div className="px-4 pb-3"><Input aria-label="Search conversations" placeholder="Search chats" value={sessionQuery} onChange={(event) => { setSessionQuery(event.target.value); setSessionLimit(50) }} /></div> : null}
    <div className="scroll-slim min-h-0 flex-1 space-y-1 overflow-y-auto px-3"><ResourceNotice resource={model.sessions} label="Sessions" />{model.sessions.status === 'ready' ? listed.length ? <>{listed.slice(0, sessionLimit).map((session) => <button key={session.id} type="button" aria-label={`Open ${session.title}`} aria-current={selected?.id === session.id ? 'page' : undefined} onClick={() => { model.openSession(session.id); setTab('chat'); setNavOpen(false) }} className={`flex w-full cursor-pointer items-start gap-2.5 rounded-xl px-3 py-3 text-left transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${selected?.id === session.id ? 'bg-primary/8 text-foreground' : 'text-muted-foreground hover:bg-muted'}`}>{session.kind === 'research' ? <BookOpen className="mt-0.5 size-4 shrink-0" aria-hidden /> : <MessageCircle className="mt-0.5 size-4 shrink-0" aria-hidden />}<span className="min-w-0"><span className="block truncate text-xs font-medium" title={session.title}>{session.title}</span>{session.kind === 'research' ? <span className="mt-1 block text-[11px] text-muted-foreground">{stateLabel[sector.state]}</span> : null}</span></button>)}{listed.length > sessionLimit ? <Button variant="ghost" size="sm" onClick={() => setSessionLimit((limit) => limit + 50)}>Show more ({sessionLimit} of {listed.length})</Button> : null}</> : <div className="rounded-lg border border-dashed border-border p-3 text-xs text-muted-foreground">{sessionQuery ? 'No matching conversations.' : 'Start a chat to brainstorm alongside research.'}</div> : null}</div>
    <div className="flex items-center justify-between border-t border-border p-4"><span className="text-xs text-muted-foreground">Sector workspace</span><Button variant="ghost" size="icon" aria-label={dark ? 'Use light theme' : 'Use dark theme'} onClick={onTheme}>{dark ? <Sun className="size-4" aria-hidden /> : <Moon className="size-4" aria-hidden />}</Button></div>
  </div>
  const resourceRail = <div className="flex h-full min-h-0 flex-col divide-y divide-border"><WorkspaceFiles resource={model.files} busy={busy} onUpload={(file) => void model.upload(file)} onHide={(id, hidden) => void model.hideFile(id, hidden)} onInclude={(id) => void model.includeFile(id)} onPreview={model.previewFile} /><GlobalContextPanel preview={model.preview} onReview={model.reviewProposal} resource={model.global} busy={busy} error={model.error} onSave={model.saveGlobal} onDecision={model.decide} /></div>
  return <div className="grid h-dvh min-h-0 grid-cols-1 overflow-hidden bg-background md:grid-cols-[240px_minmax(0,1fr)] xl:grid-cols-[240px_minmax(0,1fr)_320px]">
    <aside aria-label="Sector sessions" className="hidden min-h-0 border-r border-border bg-muted/20 md:block">{sessionRail}</aside>
    <main className="flex min-h-0 min-w-0 flex-col">
      <header className="flex shrink-0 items-center gap-3 border-b border-border px-4 py-4 sm:px-6"><Button variant="ghost" size="icon" aria-label="Open sessions" className="md:hidden" onClick={() => setNavOpen(true)}><Menu className="size-4" aria-hidden /></Button>{model.child ? <Button variant="ghost" size="icon" aria-label="Back to parent conversation" onClick={() => selected && model.openThread(selected.id)}><ArrowLeft className="size-4" aria-hidden /></Button> : null}<div className="min-w-0 flex-1"><p className="mb-1 text-[10px] uppercase tracking-wider text-muted-foreground">{model.child ? 'Subagent' : selected?.kind === 'research' ? 'Research session' : 'Conversation'}</p><h1 className="truncate text-sm font-semibold">{model.child ? model.child.name ?? 'Research agent' : selected?.title ?? 'Sector workspace'}</h1></div><Button variant="ghost" size="icon" className="xl:hidden" aria-label="Open files and global context" onClick={() => setResourcesOpen(true)}><FolderOpen className="size-4" aria-hidden /></Button><Button variant="ghost" size="icon" aria-label="Conversation options" disabled={!selected} onClick={() => setOptions(true)}><MoreHorizontal className="size-4" aria-hidden /></Button></header>
      {selected?.kind === 'research' && !model.child ? <><div className="flex shrink-0 items-center gap-3 border-b border-border px-4 sm:px-6"><div role="tablist" aria-label="Research views" className="flex gap-4">{(['chat','plan'] as const).map((value) => <button type="button" key={value} role="tab" aria-selected={tab === value} onClick={() => setTab(value)} className={`cursor-pointer border-b-2 py-3 text-xs font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${tab === value ? 'border-primary text-foreground' : 'border-transparent text-muted-foreground hover:text-foreground'}`}>{value === 'chat' ? 'Chat' : 'Plan'}</button>)}</div><div className="flex-1" /><ResearchControl state={sector.state} actions={actions} /><span className="hidden text-xs text-muted-foreground sm:block">{stateLabel[sector.state]}</span></div></> : null}
      {children.length ? <div className="flex shrink-0 items-center gap-2 border-b border-border px-4 py-2 text-xs sm:px-6"><GitBranch className="size-3.5 text-muted-foreground" aria-hidden /><div className="scroll-slim flex min-w-0 flex-1 gap-1 overflow-x-auto">{children.slice(0, 3).map((child) => <Button key={child.key} variant="ghost" size="sm" className="h-8 shrink-0 text-xs" onClick={() => model.openThread(child.key)}><span aria-hidden className={`size-1.5 rounded-full ${child.status === 'RUNNING' ? 'bg-primary' : 'bg-muted-foreground/40'}`} />{child.name ?? 'Research agent'}</Button>)}</div><Button variant="ghost" size="sm" onClick={() => setDirectory(true)}>All {children.length}<ChevronRight className="size-3" aria-hidden /></Button></div> : null}
      {model.error || actions.error ? <p role="alert" className="m-3 rounded-lg border border-border bg-muted/30 p-3 text-xs">{model.error ?? actions.error}</p> : null}
      {tab === 'plan' && !model.child && selected?.kind === 'research' ? <div role="tabpanel" aria-label="Research plan" className="scroll-slim min-h-0 flex-1 overflow-y-auto p-5 sm:p-8"><div className="mx-auto max-w-3xl space-y-6"><ResourceNotice resource={model.plan} label="Research plan" />{model.plan.status === 'ready' && model.plan.data?.latest ? <section className="rounded-xl border border-border p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-semibold">Research plan</h2><span className="font-mono text-xs text-muted-foreground">v{model.plan.data.latest.version}</span></div><Markdown text={model.plan.data.latest.markdown} />{model.plan.data.latest.executable ? <ExecutablePlanDetails plan={model.plan.data.latest.executable} /> : null}{sector.state === 'planned' ? <Button className="mt-4" disabled={actions.busy} onClick={() => actions.approve(model.plan.data?.latest?.version ?? 0)}>Approve plan</Button> : null}{['planned', 'approved', 'paused'].includes(sector.state) ? <ResearchPlanEditor markdown={model.plan.data.latest.markdown} executable={model.plan.data.latest.executable} busy={actions.busy} error={actions.error} onSave={actions.edit} /> : null}</section> : model.plan.status === 'ready' ? <div className="rounded-xl border border-dashed border-border p-6"><p className="text-sm text-muted-foreground">Create a plan before research begins.</p><Button className="mt-4" disabled={actions.busy} onClick={actions.plan}>Create plan</Button></div> : null}<PlanProgress resource={model.progress} /></div></div> : <ConversationView key={model.activeThread} model={model} config={config} onContext={() => setContextOpen(true)} />}
    </main>
    <aside aria-label="Sector resources" className="hidden min-h-0 border-l border-border bg-muted/10 xl:block">{resourceRail}</aside>
    {navOpen ? <WorkspaceOverlay title="Sessions" side onClose={() => setNavOpen(false)}>{sessionRail}</WorkspaceOverlay> : null}
    {resourcesOpen ? <WorkspaceOverlay title="Files and global context" side onClose={() => setResourcesOpen(false)}><div className="flex h-[calc(100dvh-180px)] min-h-0 flex-col">{resourceRail}</div></WorkspaceOverlay> : null}
    {contextOpen ? <WorkspaceOverlay title="Local context" onClose={() => setContextOpen(false)}><LocalContextEditor key={model.activeThread} resource={model.local} busy={busy} error={model.error} onSave={(notes, version) => void model.saveLocal(notes, version)} onCompact={() => void model.compact()} /></WorkspaceOverlay> : null}
    {directory ? <WorkspaceOverlay title="Subagents" onClose={() => setDirectory(false)}><AgentDirectory model={model} onOpen={(key) => { model.openThread(key); setDirectory(false) }} /></WorkspaceOverlay> : null}
    {model.previewFileId ? <WorkspaceOverlay title="File preview" onClose={() => model.previewFile(null)}><SectorFilePreview resource={model.fileBody} /></WorkspaceOverlay> : null}
    {options && selected ? <WorkspaceOverlay title="Conversation options" onClose={() => setOptions(false)}><SessionOptions title={selected.title} research={selected.kind === 'research'} busy={busy} onRename={(title) => { void model.renameChat(title); setOptions(false) }} onDelete={() => { void model.deleteChat(); setOptions(false) }} /></WorkspaceOverlay> : null}
  </div>
}
function ResearchControl({ state, actions }: { state: ResearchState; actions: ResearchActions }) {
  const action = state === 'draft' || state === 'failed' ? { label: 'Create plan', click: actions.plan, icon: BookOpen } : state === 'approved' ? { label: 'Start research', click: actions.start, icon: Play } : state === 'running' ? { label: 'Pause research', click: actions.pause, icon: Pause } : state === 'paused' ? { label: 'Resume research', click: actions.resume, icon: Play } : null
  return action ? <Button variant="ghost" size="icon" aria-label={action.label} disabled={actions.busy} onClick={action.click}><action.icon className="size-4" aria-hidden /></Button> : null
}
const scrollPositions = new Map<string, number>()
function ConversationView({ model, config, onContext }: { model: SectorWorkspaceModel; config: StagingConfig; onContext(): void }) {
  const chat = model.chat
  const { listRef, showLatest, onListScroll, jumpToLatest } = useChatStick(`${model.activeThread}:${chat.messages.length}:${chat.live?.pendingText?.length ?? 0}`)
  const composer = useRef<HTMLTextAreaElement>(null)
  useEffect(() => { composer.current?.focus(); const position = scrollPositions.get(model.activeThread ?? ''); if (position !== undefined && listRef.current) listRef.current.scrollTop = position }, [model.activeThread, listRef])
  const tools = (chat.live?.pendingTools ?? []).map((tool) => ({ id: tool.id, kind: 'tool' as const, name: tool.name, detail: '', state: tool.state }))
  const notice = { status: chat.status, refresh: chat.retry, error: chat.error ?? undefined }
  return <div className="flex min-h-0 flex-1 flex-col"><div className="relative min-h-0 flex-1"><div ref={listRef} onScroll={() => { onListScroll(); if (listRef.current) scrollPositions.set(model.activeThread ?? '', listRef.current.scrollTop) }} role="log" aria-label="Conversation messages" aria-live="polite" className="scroll-slim h-full overflow-y-auto px-4 py-6 sm:px-8"><div className="mx-auto max-w-3xl space-y-6"><ResourceNotice resource={notice} label="Conversation" />{chat.status === 'ready' && chat.messages.length === 0 && !chat.echo ? <div className="mx-auto mt-16 max-w-sm rounded-2xl border border-dashed border-border bg-muted/10 p-8 text-center"><MessageCircle className="mx-auto mb-4 size-6 text-muted-foreground" aria-hidden /><h2 className="text-base font-medium">Space to think</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Ask a question, explore an idea, or work with the sector’s files and shared context.</p></div> : null}
    {groupMessageSegments(chat.messages).map((segment) => 'tools' in segment ? <div key={segment.key}><ActivityGroup tools={segment.tools} reasoning={segment.reply?.reasoning} />{segment.reply ? <AgentBubble><Markdown text={segment.reply.text} /></AgentBubble> : null}</div> : segment.message.kind === 'text' ? segment.message.role === 'user' ? <UserBubble key={segment.message.id}>{segment.message.text}</UserBubble> : <div key={segment.message.id}>{segment.message.reasoning ? <ActivityGroup tools={[]} reasoning={segment.message.reasoning} /> : null}<AgentBubble><Markdown text={segment.message.text} /></AgentBubble></div> : null)}
    {chat.echo ? <UserBubble>{chat.echo}</UserBubble> : null}{tools.length || chat.live?.pendingReasoning ? <ActivityGroup tools={tools} reasoning={chat.live?.pendingReasoning ?? undefined} live /> : null}{chat.live?.pendingText ? <AgentBubble><Markdown text={chat.live.pendingText} /></AgentBubble> : null}{chat.phase === 'queued' ? <p role="status" className="rounded-lg bg-muted/30 p-3 text-xs text-muted-foreground">Queued for the agent</p> : chat.phase === 'reconnecting' ? <p role="status" className="rounded-lg bg-muted/30 p-3 text-xs text-muted-foreground">Reconnecting. Your conversation is saved.</p> : chat.busy && !chat.live?.pendingText && !tools.length && !chat.live?.pendingReasoning ? <ThinkingPlaceholder /> : null}{chat.phase === 'paused' || model.threads.data?.find((thread) => thread.key === model.activeThread)?.status === 'PAUSED' ? <div role="status" className="space-y-3 rounded-lg border border-border p-3 text-sm"><p>This conversation is paused. Review local context, then resume the saved turn.</p><Button disabled={Boolean(model.operation)} onClick={() => void model.resume()}>Resume conversation</Button></div> : null}
  </div></div>{showLatest ? <Button size="sm" variant="outline" className="absolute bottom-3 left-1/2 -translate-x-1/2 rounded-full shadow-sm" onClick={jumpToLatest}>Latest</Button> : null}</div>
  <div className="shrink-0 px-4 pt-3 pb-5 sm:px-8"><div className="mx-auto max-w-3xl"><div className="rounded-2xl border border-border bg-muted/20 p-2.5 shadow-sm focus-within:border-primary/40"><label htmlFor="workspace-composer" className="sr-only">Message this conversation</label><textarea ref={composer} id="workspace-composer" rows={2} value={chat.draft} onChange={(event) => chat.setDraft(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey && !chat.busy) { event.preventDefault(); void chat.send() } }} placeholder={model.child ? 'Steer or chat with this subagent…' : 'Message…'} disabled={!model.activeThread || chat.status === 'denied'} className="scroll-slim block max-h-40 w-full resize-none border-0 bg-transparent px-2 py-1.5 text-sm leading-relaxed focus:outline-none disabled:opacity-50" />
    <div className="flex flex-wrap items-center gap-1"><Button variant="ghost" size="icon" aria-label="Local context" onClick={onContext}><BookOpen className="size-4" aria-hidden /></Button>{model.selected ? <ModelToolbar config={config} sessionId={model.selected.id} bare /> : null}<div className="flex-1" />{chat.busy ? <><Button variant="ghost" size="sm" disabled={!chat.draft.trim()} onClick={() => void chat.send(true)}>Steer this turn</Button><Button variant="ghost" size="sm" disabled={!chat.draft.trim()} onClick={() => void chat.send()}>Send next turn</Button><Button variant="outline" size="icon" aria-label="Stop agent" disabled={Boolean(model.operation)} onClick={() => void model.stop()}><Square className="size-3.5" aria-hidden /></Button></> : <Button size="icon" aria-label="Send message" title="Enter to send · Shift+Enter for a new line" disabled={!chat.draft.trim() || !model.activeThread} onClick={() => void chat.send()} className="rounded-xl"><ArrowUp className="size-4" aria-hidden /></Button>}</div>
  </div>{chat.missedInstructions.length ? <section aria-label="Unapplied steering" className="mt-2 rounded-lg border border-border p-3 text-xs"><p className="font-medium">Steering saved for your next turn</p>{chat.missedInstructions.map((text, index) => <p key={index} className="mt-2 whitespace-pre-wrap break-words">{text}</p>)}</section> : null}{chat.phase === 'reconnecting' ? <Button variant="outline" size="sm" className="mt-2" onClick={chat.retry}>Reconnect conversation</Button> : null}{chat.error ? <p role="alert" className="mt-2 rounded-lg border border-border bg-muted/30 p-3 text-xs">{chat.error}</p> : null}</div></div></div>
}
function AgentDirectory({ model, onOpen }: { model: SectorWorkspaceModel; onOpen(key: string): void }) {
  const [search, setSearch] = useState(''), [limit, setLimit] = useState(50)
  const rows = model.threads.data?.filter((thread) => thread.kind === 'subagent' && `${thread.name ?? ''} ${thread.key}`.toLowerCase().includes(search.toLowerCase())) ?? []
  return <div className="space-y-3"><div className="relative"><Search aria-hidden className="absolute top-3 left-3 size-4 text-muted-foreground" /><Input aria-label="Search subagents" placeholder="Search subagents" value={search} onChange={(event) => { setSearch(event.target.value); setLimit(50) }} className="pl-9" /></div><ResourceNotice resource={model.threads} label="Subagents" /><p className="rounded bg-muted p-2 text-xs text-muted-foreground">Showing {Math.min(limit, rows.length)} of {rows.length}</p>{rows.slice(0, limit).map((thread) => <button type="button" key={thread.key} onClick={() => onOpen(thread.key)} className="flex w-full cursor-pointer items-center gap-3 rounded-lg border border-border p-3 text-left hover:bg-muted focus-visible:ring-2 focus-visible:ring-ring"><GitBranch className="size-4" aria-hidden /><span className="min-w-0 flex-1 truncate text-sm">{thread.name ?? 'Research agent'}</span><span className="text-xs capitalize text-muted-foreground">{thread.status.toLowerCase()}</span></button>)}{!rows.length && model.threads.status === 'ready' ? <p className="rounded-lg border border-dashed border-border p-4 text-sm">No matching subagents.</p> : null}{rows.length > limit ? <Button variant="outline" onClick={() => setLimit(limit + 50)}>Show more</Button> : null}</div>
}
function SessionOptions({ title, research, busy, onRename, onDelete }: { title: string; research: boolean; busy: boolean; onRename(title: string): void; onDelete(): void }) {
  const [name, setName] = useState(title), [confirm, setConfirm] = useState(false)
  return <div className="space-y-4"><label className="block text-sm font-medium">Conversation name<Input value={name} onChange={(event) => setName(event.target.value)} className="mt-2" /></label><Button disabled={busy || !name.trim()} onClick={() => onRename(name.trim())}>Save name</Button>{!research ? <div className="rounded-lg border border-border p-3"><p className="mb-2 text-xs text-muted-foreground">{confirm ? 'Delete this conversation? Its history is retained in the audit log.' : 'Remove this conversation from the session list.'}</p><Button variant="outline" disabled={busy} onClick={() => { if (confirm) onDelete(); else setConfirm(true) }}>{confirm ? 'Confirm deletion' : 'Delete conversation'}</Button></div> : null}</div>
}
