import { useEffect, useId, useRef, useState, type ReactNode } from 'react'
import { Check, Eye, EyeOff, FileText, History, Layers3, Pencil, Plus, Search, Upload, X } from 'lucide-react'
import { Button } from './ui/button'
import { Input } from './ui/input'
import { Markdown, safeExternalUrl } from './Markdown'
import type { Resource } from '../data/useWorkspace'
import type { ContextPreview, GlobalContext, LibraryFile, LocalContext, ResearchProgress, Sections } from '../data/workspace-api'

export function WorkspaceOverlay({ title, children, onClose, side = false, footer }: { title: string; children: ReactNode; onClose(): void; side?: boolean; footer?: ReactNode }) {
  const ref = useRef<HTMLDialogElement>(null)
  const id = useId()
  useEffect(() => {
    const previous = document.activeElement
    const dialog = ref.current
    if (dialog && !dialog.open) { if (dialog.showModal) dialog.showModal(); else dialog.setAttribute('open', '') }
    return () => {
      if (dialog?.open && dialog.close) dialog.close()
      requestAnimationFrame(() => { if (previous instanceof HTMLElement && previous.isConnected) previous.focus() })
    }
  }, [])
  return <dialog ref={ref} aria-labelledby={id} onCancel={(event) => { event.preventDefault(); onClose() }} onClick={(event) => { if (event.target === event.currentTarget) onClose() }} className={`fixed inset-0 z-50 m-auto max-h-[85dvh] w-[min(92vw,720px)] overflow-hidden rounded-2xl border border-border bg-background p-0 text-foreground shadow-xl backdrop:bg-foreground/20 ${side ? 'mr-0 h-dvh max-h-dvh w-[min(92vw,360px)] rounded-r-none' : ''}`}>
    <div className="flex items-center justify-between border-b border-border px-5 py-4"><h2 id={id} className="text-base font-semibold">{title}</h2><Button variant="ghost" size="icon" aria-label={`Close ${title}`} onClick={onClose}><X className="size-4" aria-hidden /></Button></div>
    <div className={`scroll-slim overflow-y-auto p-5 ${footer ? 'max-h-[calc(85dvh-160px)]' : 'max-h-[calc(85dvh-80px)]'}`}>{children}</div>
    {footer ? <div className="flex items-center justify-end gap-2 border-t border-border bg-background px-5 py-4">{footer}</div> : null}
  </dialog>
}
export function ResourceNotice({ resource, label }: { resource: Resource<unknown>; label: string }) {
  if (resource.status === 'ready') return null
  if (resource.status === 'loading') return <div role="status" aria-label={`${label} is loading`} className="space-y-3 rounded-lg border border-border/60 p-4"><div className="h-3 w-2/3 rounded bg-muted motion-safe:animate-pulse" /><div className="h-3 w-full rounded bg-muted motion-safe:animate-pulse" /><span className="sr-only">Loading {label}</span></div>
  const text = resource.status === 'denied' ? `${label} is not shared with this key.` : resource.status === 'offline' ? 'No connection. Reconnect and try again.' : resource.error ?? `${label} did not load.`
  return <div role="alert" className="rounded-lg border border-border bg-muted/30 p-3 text-sm"><p>{text}</p><Button variant="ghost" size="sm" className="mt-2" onClick={resource.refresh}>Try again</Button></div>
}
export function PlanProgress({ resource }: { resource: Resource<ResearchProgress> }) {
  const [search, setSearch] = useState(''), [limit, setLimit] = useState(50)
  const terminalWithoutLedger = resource.data && ['complete', 'failed'].includes(resource.data.state) && resource.data.items.length === 0
  const rows = resource.data?.items.filter((item) => `${item.title} ${item.detail}`.toLowerCase().includes(search.toLowerCase())) ?? []
  return <section aria-label="Research progress" className="space-y-4"><ResourceNotice resource={resource} label="Research progress" />{resource.status === 'ready' && resource.data ? <>
    <div className="rounded-xl border border-border bg-muted/30 p-4"><div className="flex items-center justify-between gap-3"><span className="text-sm font-medium">Approved work</span><span className="font-mono text-xs tabular-nums">{resource.data.estimatedPercent === null ? 'Estimate pending' : `Estimated ${resource.data.estimatedPercent}%`}</span></div>
      {resource.data.estimatedPercent !== null ? <progress aria-label="Estimated completion" max={100} value={resource.data.estimatedPercent} className="mt-3 h-1.5 w-full accent-primary" /> : null}
      <p className="mt-2 text-xs text-muted-foreground">{resource.data.completed} of {resource.data.total} work items completed{resource.data.unresolved ? ` · ${resource.data.unresolved} need attention` : ''}</p>
      {resource.data.budgetUsedMs !== undefined ? <p className="mt-2 text-xs text-muted-foreground">{Math.round(resource.data.budgetUsedMs / 6000) / 10} active minutes recorded across research runs</p> : null}
      {!resource.data.discoveryClosed && !terminalWithoutLedger ? <p className="mt-2 text-xs text-muted-foreground">The estimate becomes available when discovery has bounded the remaining work.</p> : null}
    </div>
    {resource.data.items.length ? <><Input aria-label="Search research work" placeholder="Search work items" value={search} onChange={(event) => { setSearch(event.target.value); setLimit(50) }} /><p className="text-xs text-muted-foreground">Showing {Math.min(limit, rows.length)} of {rows.length} work items</p><ol className="scroll-slim max-h-80 space-y-2 overflow-y-auto">{rows.slice(0, limit).map((item) => <li key={item.id} className="rounded-lg border border-border p-3"><div className="flex items-start gap-2"><span aria-hidden className={`mt-1 size-2 shrink-0 rounded-full ${item.state === 'complete' ? 'bg-primary' : item.state === 'running' ? 'bg-primary/50' : 'bg-muted-foreground/30'}`} /><span className="min-w-0 flex-1 text-sm [overflow-wrap:anywhere]">{item.title}</span><span className="text-xs capitalize text-muted-foreground">{item.state}</span></div>{item.detail ? <p className="mt-2 text-xs text-muted-foreground">{item.detail}</p> : null}{item.sourceUrl ? <a href={safeExternalUrl(item.sourceUrl)} target="_blank" rel="noopener noreferrer" className="mt-2 inline-block text-xs text-primary underline underline-offset-2 focus-visible:ring-2 focus-visible:ring-ring">Company source</a> : null}</li>)}</ol>{rows.length > limit ? <Button variant="outline" size="sm" onClick={() => setLimit((value) => value + 50)}>Show more work items</Button> : null}{!rows.length ? <p className="text-sm text-muted-foreground">No matching work items.</p> : null}</> : <p className="rounded-lg border border-dashed border-border p-4 text-sm text-muted-foreground">{terminalWithoutLedger ? 'No work-item ledger was recorded for this run. Saved companies and conversations remain available.' : 'Work items appear when the approved research starts.'}</p>}
  </> : null}</section>
}
export function GlobalContextPanel({ resource, preview, busy, error, onReview, onSave, onDecision }: { resource: Resource<GlobalContext>; preview: Resource<ContextPreview>; busy: boolean; error?: string | null; onReview(id: string | null): void; onSave(sections: Sections, version: number): Promise<boolean>; onDecision(id: string, approve: boolean): Promise<boolean> }) {
  const [editor, setEditor] = useState(false), [history, setHistory] = useState(false), [proposal, setProposal] = useState<string | null>(null)
  const pending = resource.data?.changes.filter((change) => change.state === 'pending' || change.state === 'parent-review') ?? []
  const [editContext, setEditContext] = useState<GlobalContext | null>(null)
  if (editor && !resource.data) { setEditor(false); setEditContext(null) }
  return <section aria-label="Global context" className="flex min-h-0 flex-1 flex-col">
    <div className="flex shrink-0 items-center gap-1 border-b border-border px-4 py-3"><h2 className="min-w-0 flex-1 text-sm font-semibold">Global context</h2><Button variant="ghost" size="icon-sm" aria-label="Context history" disabled={!resource.data} onClick={() => setHistory(true)}><History className="size-4" aria-hidden /></Button><Button variant="ghost" size="icon-sm" aria-label="Edit global context" disabled={!resource.data} onClick={() => { setEditContext(resource.data ?? null); setEditor(true) }}><Pencil className="size-4" aria-hidden /></Button></div>
    <div className="scroll-slim min-h-0 flex-1 space-y-4 overflow-y-auto p-4"><ResourceNotice resource={resource} label="Global context" />{resource.status === 'ready' && resource.data ? <>
      <div className="rounded-lg border border-border/60 bg-muted/20 p-3"><Markdown text={resource.data.markdown || 'No shared context yet. Add the sector scope and decisions here.'} /></div>
      {pending.length ? <div className="space-y-2"><p className="rounded-md bg-muted px-2 py-1 text-xs font-medium">{pending.length} pending {pending.length === 1 ? 'update' : 'updates'}</p>{pending.map((change) => <button key={change.id} type="button" onClick={() => { setProposal(change.id); onReview(change.id) }} className="flex w-full cursor-pointer items-center justify-between gap-2 rounded-lg border border-border p-3 text-left text-xs hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><span>{change.fileRef ? 'File context inclusion' : 'Shared context update'}</span><span className="text-primary">Review</span></button>)}</div> : null}
    </> : null}</div>
    {editor && editContext ? <WorkspaceOverlay title="Edit global context" onClose={() => setEditor(false)}><ContextEditor key={editContext.version} sections={editContext.sections} busy={busy} error={error} onSave={async (sections) => { if (await onSave(sections, editContext.version)) setEditor(false) }} /></WorkspaceOverlay> : null}
    {history && resource.data ? <WorkspaceOverlay title="Context history" onClose={() => setHistory(false)}><ol className="space-y-3">{resource.data.changes.length ? resource.data.changes.map((change) => <li key={change.id} className="rounded-lg border border-border p-3"><div className="flex justify-between gap-2 text-xs"><span>{change.author} · {change.state}</span><time>{new Date(change.at).toLocaleString()}</time></div><Markdown text={Object.entries(change.sections).filter(([, text]) => text).map(([key, text]) => `### ${key}\n${text}`).join('\n\n')} /></li>) : <p className="rounded-lg border border-dashed border-border p-4 text-sm">No revisions yet.</p>}</ol></WorkspaceOverlay> : null}
    {proposal && resource.data ? <WorkspaceOverlay title="Review context update" onClose={() => { setProposal(null); onReview(null) }}>{resource.data.changes.filter((change) => change.id === proposal).map((change) => <div key={change.id} className="space-y-4"><p className="rounded-lg bg-muted p-3 text-xs">Based on v{change.baseVersion} · Current v{resource.data?.version}{change.fileRef ? ` · ${change.fileRef.filename}` : ''}</p>{change.fileRef ? <div className="space-y-3"><ResourceNotice resource={preview} label="File inclusion preview" />{preview.status === 'ready' && preview.data ? <><p className="rounded-lg bg-muted p-3 text-xs">Approve these {preview.data.units.length} units from {change.fileRef.filename}. This exact file version will be shared.</p>{preview.data.units.map((unit) => <section key={unit.ord} className="rounded-lg border border-border p-3"><h3 className="mb-2 text-xs font-medium">{change.fileRef?.filename}:{unit.ord}{unit.uncertain ? ' · Uncertain extraction' : ''}</h3><Markdown text={unit.text} /></section>)}</> : null}</div> : null}{(['scope','decisions','findings','questions'] as const).filter((key) => change.sections[key] !== resource.data?.sections[key]).map((key) => <section key={key} className="rounded-lg border border-border p-3"><h3 className="text-sm font-medium capitalize">{key}</h3><div className="mt-2 rounded bg-muted p-2 text-xs"><span className="font-medium">Current</span><Markdown text={resource.data?.sections[key] || 'Empty'} /></div><div className="mt-2 rounded border border-primary/30 p-2 text-xs"><span className="font-medium">Proposed</span><Markdown text={change.sections[key] || 'Empty'} /></div></section>)}{error ? <p role="alert" className="rounded-lg bg-muted p-3 text-xs">{error}</p> : null}<div className="flex gap-2"><Button disabled={busy || change.baseVersion !== resource.data?.version || (Boolean(change.fileRef) && preview.status !== 'ready')} onClick={async () => { if (await onDecision(change.id, true)) setProposal(null) }}><Check className="size-4" aria-hidden />Approve</Button><Button variant="outline" disabled={busy} onClick={async () => { if (await onDecision(change.id, false)) setProposal(null) }}>Reject</Button></div></div>)}</WorkspaceOverlay> : null}
  </section>
}
function ContextEditor({ sections, busy, error, onSave }: { sections: Sections; busy: boolean; error?: string | null; onSave(sections: Sections): Promise<void> }) {
  const [draft, setDraft] = useState(sections)
  return <form className="space-y-4" onSubmit={(event) => { event.preventDefault(); void onSave(draft) }}>{(['scope','decisions','findings','questions'] as const).map((key) => <label key={key} className="block text-sm font-medium capitalize">{{ scope: 'Scope', decisions: 'Decisions', findings: 'Findings', questions: 'Open questions' }[key]}<textarea value={draft[key]} onChange={(event) => setDraft({ ...draft, [key]: event.target.value })} rows={3} className="mt-2 block w-full rounded-lg border border-border bg-background px-3 py-2 text-sm font-normal focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" /></label>)}{error ? <p role="alert" className="rounded-lg bg-muted p-3 text-xs">{error}</p> : null}<Button type="submit" disabled={busy}>Save context</Button></form>
}
export function WorkspaceFiles({ resource, busy, onUpload, onHide, onInclude, onPreview }: { resource: Resource<LibraryFile[]>; busy: boolean; onUpload(file: File): void; onHide(id: string, hidden: boolean): void; onInclude(id: string): void; onPreview?(id: string): void }) {
  const [search, setSearch] = useState(''), [hidden, setHidden] = useState(false)
  const fileInput = useRef<HTMLInputElement>(null)
  const rows = resource.data?.filter((file) => (hidden || !file.hidden) && file.filename.toLowerCase().includes(search.toLowerCase())) ?? []
  return <section aria-label="Sector files" className="flex min-h-0 flex-1 flex-col"><div className="flex shrink-0 items-center justify-between border-b border-border px-4 py-3"><h2 className="text-sm font-semibold">Files</h2><Button variant="ghost" size="icon-sm" aria-label="Upload file" disabled={busy} onClick={() => fileInput.current?.click()}><Upload className="size-4" aria-hidden /></Button><input ref={fileInput} type="file" className="hidden" accept=".md,.txt,.csv,.json,.pdf,.docx,.png,.jpg,.jpeg,.webp,.gif" onChange={(event) => { const file = event.target.files?.[0]; event.target.value = ''; if (file) onUpload(file) }} /></div>
    <div className="flex shrink-0 items-center gap-2 px-4 pt-3"><div className="relative min-w-0 flex-1"><Search aria-hidden className="absolute top-2.5 left-2.5 size-3.5 text-muted-foreground" /><Input aria-label="Search files" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search files" className="h-9 pl-8 text-xs" /></div><Button variant="ghost" size="icon" aria-label={hidden ? 'Hide hidden files' : 'Show hidden files'} aria-pressed={hidden} onClick={() => setHidden(!hidden)}><EyeOff className="size-4" aria-hidden /></Button></div>
    <div className="scroll-slim min-h-0 flex-1 space-y-1 overflow-y-auto p-3"><ResourceNotice resource={resource} label="Files" />{resource.status === 'ready' ? rows.length ? rows.map((file) => <div key={file.id} className="group rounded-lg border border-transparent px-2 py-2.5 hover:border-border hover:bg-muted/30"><div className="flex items-start gap-2"><FileText className="mt-0.5 size-4 shrink-0 text-muted-foreground" aria-hidden /><div className="min-w-0 flex-1"><button type="button" disabled={file.hidden || !onPreview} onClick={() => onPreview?.(file.id)} title={file.filename} className="block w-full cursor-pointer truncate text-left text-xs font-medium hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-default">{file.filename}</button><p className="mt-1 truncate text-[11px] text-muted-foreground">{file.hidden ? 'Hidden from agents' : file.status === 'indexed' ? file.included ? 'In shared context' : file.source : file.status}</p></div><Button variant="ghost" size="icon-sm" aria-label={`${file.hidden ? 'Reveal' : 'Hide'} ${file.filename}`} disabled={busy} onClick={() => onHide(file.id, !file.hidden)}>{file.hidden ? <EyeOff className="size-3.5" aria-hidden /> : <Eye className="size-3.5" aria-hidden />}</Button>{!file.hidden && !file.included && file.status === 'indexed' ? <Button variant="ghost" size="icon-sm" aria-label={`Request context inclusion for ${file.filename}`} disabled={busy} onClick={() => onInclude(file.id)}><Plus className="size-3.5" aria-hidden /></Button> : null}</div></div>) : <div className="rounded-lg border border-dashed border-border p-4 text-center text-xs text-muted-foreground">{search ? 'No matching files.' : 'Upload source material or ask an agent to create a file.'}</div> : null}</div>
  </section>
}
export function LocalContextEditor({ resource, busy, error, onSave, onCompact }: { resource: Resource<LocalContext>; busy: boolean; error?: string | null; onSave(notes: string, version: number): void; onCompact(): void }) {
  const [notes, setNotes] = useState(resource.data?.notes ?? '')
  const [version, setVersion] = useState<number | null>(resource.data?.version ?? null)
  if (version === null && resource.data) { setVersion(resource.data.version); setNotes(resource.data.notes) }
  return <div className="space-y-4"><ResourceNotice resource={resource} label="Local context" />{resource.status === 'ready' && resource.data ? <><div className="rounded-lg bg-muted/30 p-3 text-xs text-muted-foreground">Private working memory for this conversation. The visible transcript stays intact.</div>{resource.data.usage ? <div className="rounded-lg border border-border p-3"><p className="text-xs font-medium">Last request {resource.data.usage.method === 'estimated' ? 'estimate' : 'input'}</p><p className="mt-1 font-mono text-xs tabular-nums text-muted-foreground">{resource.data.usage.inputTokens.toLocaleString()} / {resource.data.usage.budget.toLocaleString()} budget · {resource.data.usage.window.toLocaleString()} window</p></div> : null}{resource.data.summary ? <div className="rounded-lg border border-border p-3"><h3 className="mb-2 text-xs font-medium">Working summary</h3><Markdown text={resource.data.summary} /></div> : null}<label className="block text-sm font-medium">Local notes<textarea value={notes} onChange={(event) => setNotes(event.target.value)} rows={6} className="mt-2 block w-full rounded-lg border border-border bg-background p-3 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" /></label>{error ? <p role="alert" className="rounded-lg bg-muted p-3 text-xs">{error}</p> : null}<div className="flex flex-wrap gap-2"><Button disabled={busy} onClick={() => onSave(notes, version ?? 0)}>Save notes</Button><Button variant="outline" disabled={busy} onClick={onCompact}><Layers3 className="size-4" aria-hidden />{busy ? 'Working…' : 'Compact context'}</Button></div></> : null}</div>
}
