// DB access layer barrel (B7.1). The ONLY import surface for database
// access: product code imports from '../db/index.js' (or './index.js'),
// never deep into repos and never 'pg' directly (enforced by eslint
// no-restricted-imports). Repositories land here slice by slice.
export * from './workspace.js'
export { DbContractError } from './errors.js'
export {
  type AppendedEvent,
  ARTIFACT_REFERENCED_EVENT,
  type ArtifactSummary,
  createArtifact,
  type CreateArtifactInput,
  createSession,
  type Db,
  type DbQueryResult,
  EventEnvelope,
  appendEvent,
  deleteEventsBySeq,
  deleteSession,
  findEventByKey,
  findLaunchParentWorkflowId,
  getSession,
  getSessionModel,
  listArtifacts,
  listSessions,
  listTenantArtifacts,
  readEventsAfter,
  readEventsOlderThan,
  readPartition,
  referenceArtifact,
  renameSession,
  resolveArtifactScope,
  SESSION_DELETED_EVENT,
  SESSION_MODEL_EVENT,
  SessionModelSelection,
  setSessionModel,
  type SessionRecord,
  type StoredEvent,
} from './events.js'
export {
  getThread,
  getThreadHeader,
  listThreads,
  listThreadHeaders,
  projectBatch,
  type ProjectionResult,
  rebuildFromEvents,
  cancelThreadRun,
  pauseThreadRun,
  resumeThreadRun,
  sendThreadMessage,
  steerThread,
  type ThreadMessenger,
} from './threads.js'
export {
  researchHealth,
  type ResearchHealth,
  type ResearchSessionHealth,
  type ResearchThreadHealth,
} from './research-health.js'
export {
  fleetTotals,
  type LedgerResult,
  projectUsage,
  rebuildLedger,
  runTotals,
  type UsageTotals,
} from './ledger.js'
export {
  type CheckpointTx,
  runCheckpointTx,
  type TransactableDb,
} from './checkpoints.js'
export {
  KbChunkInput,
  KbDocumentInput,
  type KbSearchHit,
  recordKbBatch,
  searchKb,
} from './knowledge.js'
export {
  getLedgerCompany,
  LedgerQualification,
  type LedgerCompany,
  type LedgerProblem,
  listLedgerCompanies,
  listLedgerProblems,
  ProblemStatus,
  recordLedgerProblem,
  RecordProblemInput,
  UpsertCompanyInput,
  upsertLedgerCompany,
  registerLedgerCandidate,
} from './company-ledger.js'
export {
  COMPANY_FOUND_EVENT,
  COMPANY_STAGE_CHANGED_EVENT,
  COMPANY_STATE_CHANGED_EVENT,
  CompanyStage,
  SECTOR_CREATED_EVENT,
  SECTOR_RESEARCH_STARTED_EVENT,
  SECTOR_PLAN_WRITTEN_EVENT,
  SECTOR_PLAN_APPROVED_EVENT,
  SECTOR_STATE_CHANGED_EVENT,
  SectorState,
  assertSectorTransition,
  SECTOR_TRANSITIONS,
  SectorTransitionError,
  type ActivityEntry,
  type CompanyFilters,
  type CompanyRecord,
  type Paging,
  type SectorFilters,
  type SectorRecord,
  type SectorTransitionFailure,
  createSector,
  getSector,
  listCompanies,
  listSectorCompanies,
  listSectors,
  markCompanyFound,
  registerSectorDiscovery,
  readSectorExecutionState,
  pauseSectorResearch,
  projectSectorEvent,
  recordResearchSession,
  resumeSectorResearch,
  sectorActivity,
  setCompanyStage,
  setCompanyState,
  setSectorState,
} from './sectors.js'
export {
  SECTOR_DOCUMENT_MAX_BYTES,
  documentExtension,
  extractDocumentText,
  ingestSectorDocument,
  listSectorDocuments,
  querySectorDocument,
  readSectorDocument,
  readOriginalSectorDocument,
  sha256Hex,
  type DocumentChunksResult,
  type DocumentSummaryResult,
  type DocumentTocEntry,
  type IngestedDocument,
  type QuerySectorDocumentInput,
  type QuerySectorDocumentResult,
  type SectorDocument,
} from './sector-documents.js'
export {
  countDocumentUnits,
  insertDocumentUnits,
  listDocumentUnits,
  type DocumentUnit,
} from './document-units.js'
export {
  SectorPlanError,
  approveSectorPlan,
  planSectorResearch,
  readSectorPlan,
  recordPlanVersion,
  updateSectorPlan,
  type SectorPlanFailure,
  type SectorPlanRunner,
  type PlanVersion,
  type SectorPlan,
} from './sector-plan.js'
export {
  SectorStartError,
  startSectorResearch,
  type SectorStartFailure,
  type SectorSweepRunner,
} from './sector-start.js'
export {
  pauseSectorSweep,
  restartSectorSweep,
  resumeSectorSweep,
} from './sector-lifecycle.js'
export {
  addContextNotes,
  buildSectorDigest,
  compactSectorContext,
  getSectorContext,
  listContextNotes,
  setUnitExclusions,
  type CompactContextResult,
  type ContextFileView,
  type ContextNoteView,
  type ContextUnitView,
  type SectorContextView,
  type SectorDigest,
  type UnitRef,
} from './sector-context.js'
export {
  chunkTextUnits,
  classifyUpload,
  createHttpOcrAdapter,
  extractFileUnits,
  OCR_CONFIDENCE_MIN,
  ScriptedOcrAdapter,
  UNIT_MAX_CHARS,
  type ClassifiedFile,
  type ExtractedUnit,
  type ExtractionStatus,
  type FileExtraction,
  type OcrAdapter,
  type OcrResult,
} from './file-pipeline.js'
export {
  DEFAULT_POOL_BUDGET,
  SERVER_POOL_BUDGET,
  WORKER_POOL_BUDGET,
  createDbPool,
  type PoolBudget,
  poolStats,
  type PoolStat,
  serverPoolBudget,
  workerPoolBudget,
  workerPoolFromEnv,
} from './pool.js'
export { findKeyByHash, registerApiKey, type KeyRecord } from './keys.js'
export {
  checkRate,
  claimIdempotency,
  completeIdempotency,
  type IdempotencyOutcome,
  type RateDecision,
  releaseIdempotency,
  sweepIdempotency,
} from './quotas.js'
export {
  HEARTBEAT_WRITE_MS,
  heartbeatThrottleKey,
  listHeartbeats,
  pruneHeartbeats,
  recordHeartbeat,
  type StoredHeartbeat,
} from './heartbeats.js'
export {
  type ConnectableDb,
  latestOutboxSeq,
  type OutboxRow,
  type OutboxSubscription,
  pruneOutbox,
  publishOutboxFrame,
  readOutboxBacklog,
  subscribeOutbox,
} from './outbox.js'
