import {randomUUID} from 'node:crypto'
import {mkdtemp} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {Pool} from 'pg'
import {describe,expect,it,vi} from 'vitest'
import {createSector,createFileProcessingJob,reserveFileProcessingDispatch,markFileProcessingDispatchOutcome,readFileProcessingJob,retryFileProcessingJob,setFileVisibility} from '../../backend/src/db/index.js'
import {FilesystemTarget} from '../../backend/src/archive/targets.js'
import {projectNewEvents} from '../../backend/src/projector.js'
import {reconcileFileAdmissionPage,inspectFileAdmissionOwner} from '../../backend/src/temporal/activities/file-admission.js'
import {ensureTestDb,TEST_DATABASE_URL} from './db-helper.js'
const scope={tenantId:'TEST admission owner',projectId:null}
async function fixture(){const pool=new Pool({connectionString:await ensureTestDb('kardata_test_file_admission')});const sectorId='sec-'+randomUUID();await createSector(pool,{sectorId,name:'TEST admission',scope});await projectNewEvents(pool);const archive=new FilesystemTarget(await mkdtemp(join(tmpdir(),'kardata-admission-')));const {job}=await createFileProcessingJob(pool,{sectorId,filename:'TEST admission.pdf',contentBase64:Buffer.from('%PDF-TEST admission').toString('base64'),provider:'meta',model:'TEST fixed model',parserVersion:'pdf-v3',promptVersion:'document-image-v2',scope,archive});return{pool,job,archive,sectorId};}
describe.skipIf(!TEST_DATABASE_URL)('durable file admission',()=>{
 it('recovers an accepted queued commit before RPC exactly once and adopts its bound owner thereafter',async()=>{const f=await fixture();try{const start=vi.fn(async(id:string,revision:number)=>{const r=await reserveFileProcessingDispatch(f.pool,id,revision);await markFileProcessingDispatchOutcome(f.pool,{jobId:id,revision,nonce:r.nonce,workflowId:r.workflowId,outcome:'confirmed',executionId:randomUUID()})});await reconcileFileAdmissionPage(f.pool,'',async()=>({state:'absent'}),start);expect(start).toHaveBeenCalledOnce();await reconcileFileAdmissionPage(f.pool,'',async()=>({state:'running',executionId:randomUUID()}),start);expect(start).toHaveBeenCalledOnce();expect((await readFileProcessingJob(f.pool,f.job.jobId)).dispatchState).toBe('confirmed')}finally{await f.pool.end()}})
 it('does not restart a reserved RPC with NOT_FOUND, and fences its late acknowledgement after owner retry',async()=>{const f=await fixture();try{const reservation=await reserveFileProcessingDispatch(f.pool,f.job.jobId,0);const start=vi.fn(async()=>{});await reconcileFileAdmissionPage(f.pool,'',async()=>({state:'absent'}),start);expect(start).not.toHaveBeenCalled();expect(await readFileProcessingJob(f.pool,f.job.jobId)).toMatchObject({state:'uncertain',retryRequiresApproval:true});await retryFileProcessingJob(f.pool,{sectorId:f.sectorId,fileId:f.job.documentId,jobId:f.job.jobId,revision:0,allowDuplicatePaid:true,author:'TEST owner',scope});await expect(markFileProcessingDispatchOutcome(f.pool,{jobId:f.job.jobId,revision:0,nonce:reservation.nonce,workflowId:reservation.workflowId,outcome:'confirmed',executionId:randomUUID()})).rejects.toMatchObject({code:'conflict'});expect(await readFileProcessingJob(f.pool,f.job.jobId)).toMatchObject({state:'queued',revision:1,dispatchState:'unreserved'})}finally{await f.pool.end()}})
 it('defers an unavailable unreserved owner without unsafe start and pauses hidden work',async()=>{const f=await fixture();try{const start=vi.fn(async()=>{});await reconcileFileAdmissionPage(f.pool,'',async()=>({state:'unavailable'}),start);expect(start).not.toHaveBeenCalled();expect((await readFileProcessingJob(f.pool,f.job.jobId)).state).toBe('queued');await setFileVisibility(f.pool,f.sectorId,f.job.documentId,true,scope);await reconcileFileAdmissionPage(f.pool,'',async()=>({state:'absent'}),start);expect((await readFileProcessingJob(f.pool,f.job.jobId)).state).toBe('paused');expect(start).not.toHaveBeenCalled()}finally{await f.pool.end()}})
})

describe.skipIf(!TEST_DATABASE_URL||process.env.KARDATA_TEMPORAL_TEST!=='1')('actual SDK admission ownership',()=>{
 it('adopts the exact type/input/nonce from an owned SDK execution and rejects mismatched inputs',async()=>{
  const f=await fixture();const [{Client},{connectClient,connectWorker},{createLaneWorker},{msToTs}]=await Promise.all([import('@temporalio/client'),import('../../backend/src/temporal/connection.js'),import('../../backend/src/temporal/worker.js'),import('@temporalio/common')]);const connection=await connectClient(),native=await connectWorker();const namespace='test-file-admission-'+randomUUID();await connection.workflowService.registerNamespace({namespace,workflowExecutionRetentionPeriod:msToTs(86400000)});const client=new Client({connection,namespace});const queue='kardata-test-file-admission-'+randomUUID();let resolve:()=>void=()=>{};const gate=new Promise<void>(r=>{resolve=r});const worker=await createLaneWorker({lane:'research',connection:native,namespace,taskQueue:queue,workflowsPath:join(import.meta.dirname,'../../backend/src/temporal/workflows/research-bundle.ts'),activities:{prepareFileProcessingActivity:async()=>{await gate;return{state:'complete'}},failFileProcessingActivity:async()=>{},fileAdmissionPageActivity:async(cursor:string)=>reconcileFileAdmissionPage(f.pool,cursor,job=>inspectFileAdmissionOwner(client,job),async()=>{throw new Error('TEST cannot dispatch twice')})}});const running=worker.run();void running.catch(()=>undefined);let handle:ReturnType<typeof client.workflow.getHandle>|undefined,supervisor:ReturnType<typeof client.workflow.getHandle>|undefined
  try{const reservation=await reserveFileProcessingDispatch(f.pool,f.job.jobId,0);handle=await client.workflow.start('fileProcessing',{workflowId:reservation.workflowId,taskQueue:queue,args:[{jobId:f.job.jobId,revision:0,dispatchNonce:reservation.nonce}]});expect(await inspectFileAdmissionOwner(client,await readFileProcessingJob(f.pool,f.job.jobId))).toMatchObject({state:'running',executionId:(await handle.describe()).runId});expect(await inspectFileAdmissionOwner(client,{...await readFileProcessingJob(f.pool,f.job.jobId),dispatchNonce:randomUUID()})).toEqual({state:'mismatch'});await markFileProcessingDispatchOutcome(f.pool,{jobId:f.job.jobId,revision:0,nonce:reservation.nonce,workflowId:reservation.workflowId,outcome:'uncertain'});supervisor=await client.workflow.start('fileAdmissionReconciliation',{workflowId:'TEST-admission-supervisor-'+randomUUID(),taskQueue:queue,args:[{}]});await vi.waitFor(async()=>expect((await readFileProcessingJob(f.pool,f.job.jobId)).dispatchState).toBe('confirmed'),{timeout:15000})}
  finally{if(supervisor){await supervisor.cancel();await supervisor.result().catch((error:unknown)=>{if(!(error instanceof Error)||!(error.cause instanceof Error)||error.cause.name!=='CancelledFailure')throw error})}resolve();try{if(handle)await handle.result()}finally{worker.shutdown();await running;await native.close();await connection.close();await f.pool.end()}}
 },60000)
})
