// Semantic icon map (plan 2.7). Feature code imports icons from here by
// meaning, never from lucide-react directly. Lucide only, stroke 1.75
// (global CSS). Sizes: 14px beside 12-13px text, 16px default, 20px in
// medallions and page-header object icons.
import {
  Activity,
  ArrowDown,
  ArrowLeft,
  ArrowUp,
  ArrowUpDown,
  ArrowUpRight,
  BookOpen,
  Bot,
  Brain,
  Building2,
  ChartNoAxesColumn,
  ChartNoAxesCombined,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  CircleAlert,
  CircleCheck,
  CirclePlus,
  CircleQuestionMark,
  CircleStop,
  ClipboardList,
  Clock,
  Command,
  Compass,
  Copy,
  Cpu,
  Download,
  Ellipsis,
  Eye,
  EyeOff,
  File,
  FileArchive,
  FileCode,
  FileImage,
  FileSpreadsheet,
  FileText,
  FlaskConical,
  FolderOpen,
  GitBranch,
  Globe,
  History,
  Inbox,
  Info,
  Layers,
  Layers3,
  LayoutDashboard,
  LayoutGrid,
  ListChecks,
  ListFilter,
  ListTree,
  Loader2,
  Lock,
  Mail,
  Menu,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Minimize2,
  Monitor,
  Moon,
  NotebookPen,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRightClose,
  PanelRightOpen,
  Paperclip,
  Pause,
  Pencil,
  Pin,
  Play,
  Plug,
  Plus,
  RefreshCw,
  RotateCcw,
  RotateCw,
  ScrollText,
  Search,
  SearchX,
  Send,
  Sparkles,
  Square,
  SquarePen,
  Sun,
  Target,
  Telescope,
  Trash2,
  TriangleAlert,
  Upload,
  Users,
  Wallet,
  WifiOff,
  Wrench,
  X,
  type LucideIcon,
} from 'lucide-react'

export const Icons = {
  sector: Layers,
  company: Building2,
  chatSession: MessagesSquare,
  researchSession: Telescope,
  chatMessage: MessageSquare,
  karbot: Sparkles,
  filePdf: FileText,
  fileMarkdown: FileText,
  fileDocs: FileText,
  fileSpreadsheet: FileSpreadsheet,
  fileImage: FileImage,
  fileCode: FileCode,
  fileArchive: FileArchive,
  fileUnknown: File,
  globalContext: Globe,
  localContext: NotebookPen,
  models: Cpu,
  runs: Activity,
  search: Search,
  moreActions: Ellipsis,
  copy: Copy,
  openExternal: ArrowUpRight,
  filter: ListFilter,
  sort: ArrowUpDown,
  themeLight: Sun,
  themeDark: Moon,
  themeSystem: Monitor,
  sidebarCollapse: PanelLeftClose,
  sidebarExpand: PanelLeftOpen,
  railHide: PanelRightClose,
  railShow: PanelRightOpen,
  alertInfo: Info,
  alertSuccess: CircleCheck,
  alertWarning: TriangleAlert,
  alertError: CircleAlert,
  denied: Lock,
  offline: WifiOff,
  notFound: SearchX,
  progress: ChartNoAxesColumn,
  overview: LayoutGrid,
  researches: FlaskConical,
  emails: Mail,
  notConnected: Plug,
  attachFile: Paperclip,
  planMode: ListTree,
  plan: ListChecks,
  executionRecords: ScrollText,
  toolActivity: Wrench,
  steer: Compass,
  stopRun: CircleStop,
  approve: Check,
  deny: X,
  edit: Pencil,
  history: History,
  upload: Upload,
  download: Download,
  hide: EyeOff,
  reveal: Eye,
  includeInContext: CirclePlus,
  includedInContext: CircleCheck,
  agents: Bot,
  thinking: Brain,
  commandPalette: Command,
  delete: Trash2,
  retry: RotateCw,
  send: ArrowUp,
  newChat: SquarePen,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  back: ArrowLeft,
  latest: ArrowDown,
  add: CirclePlus,
  loading: Loader2,
  queued: Clock,
  // Persistent additions: product concepts the 2.7 table does not name.
  budget: Wallet,
  folderOpen: FolderOpen,
  help: CircleQuestionMark,
  menu: Menu,
  minimize: Minimize2,
  pause: Pause,
  pin: Pin,
  play: Play,
  plus: Plus,
  refresh: RefreshCw,
  target: Target,
  users: Users,
  // Transitional glyphs: stages 2-6 replace each with its 2.7 semantic
  // icon when the owning surface is redesigned. Keys stay glyph-honest
  // so no call site claims a meaning the picture does not carry.
  book: BookOpen,
  chartCombined: ChartNoAxesCombined,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  clipboard: ClipboardList,
  dashboard: LayoutDashboard,
  branch: GitBranch,
  inbox: Inbox,
  layersCompact: Layers3,
  messageCircle: MessageCircle,
  sendMessage: Send,
  stopSquare: Square,
  rotateBack: RotateCcw,
} as const satisfies Record<string, LucideIcon>

export type IconName = keyof typeof Icons

/** File-type icon from a filename extension. */
export function fileIcon(filename: string): LucideIcon {
  const extension = filename.split('.').at(-1)?.toLowerCase() ?? ''
  if (extension === 'pdf' || extension === 'md' || extension === 'markdown' || extension === 'txt' || extension === 'docx') return Icons.fileDocs
  if (extension === 'csv' || extension === 'xls' || extension === 'xlsx' || extension === 'tsv') return Icons.fileSpreadsheet
  if (extension === 'png' || extension === 'jpg' || extension === 'jpeg' || extension === 'gif' || extension === 'webp' || extension === 'svg') return Icons.fileImage
  if (extension === 'json' || extension === 'js' || extension === 'ts' || extension === 'tsx' || extension === 'py' || extension === 'css' || extension === 'html') return Icons.fileCode
  if (extension === 'zip' || extension === 'tar' || extension === 'gz') return Icons.fileArchive
  return Icons.fileUnknown
}
